
//input ports
add mapped point Dclk Dclk
add mapped point Sclk Sclk
add mapped point Reset_n Reset_n
add mapped point Frame Frame
add mapped point Start Start
add mapped point InputL[15] InputL[15]
add mapped point InputL[14] InputL[14]
add mapped point InputL[13] InputL[13]
add mapped point InputL[12] InputL[12]
add mapped point InputL[11] InputL[11]
add mapped point InputL[10] InputL[10]
add mapped point InputL[9] InputL[9]
add mapped point InputL[8] InputL[8]
add mapped point InputL[7] InputL[7]
add mapped point InputL[6] InputL[6]
add mapped point InputL[5] InputL[5]
add mapped point InputL[4] InputL[4]
add mapped point InputL[3] InputL[3]
add mapped point InputL[2] InputL[2]
add mapped point InputL[1] InputL[1]
add mapped point InputL[0] InputL[0]
add mapped point InputR[15] InputR[15]
add mapped point InputR[14] InputR[14]
add mapped point InputR[13] InputR[13]
add mapped point InputR[12] InputR[12]
add mapped point InputR[11] InputR[11]
add mapped point InputR[10] InputR[10]
add mapped point InputR[9] InputR[9]
add mapped point InputR[8] InputR[8]
add mapped point InputR[7] InputR[7]
add mapped point InputR[6] InputR[6]
add mapped point InputR[5] InputR[5]
add mapped point InputR[4] InputR[4]
add mapped point InputR[3] InputR[3]
add mapped point InputR[2] InputR[2]
add mapped point InputR[1] InputR[1]
add mapped point InputR[0] InputR[0]

//output ports
add mapped point InReady InReady
add mapped point OutReady OutReady
add mapped point OutputL OutputL
add mapped point OutputR OutputR

//inout ports




//Sequential Pins
add mapped point Co_mem_L/RW0_rdata[5]/q Co_mem_L/RW0_rdata_reg[5]/Q 
add mapped point Co_mem_L/RW0_rdata[7]/q Co_mem_L/RW0_rdata_reg[7]/Q 
add mapped point Co_mem_L/RW0_rdata[8]/q Co_mem_L/RW0_rdata_reg[8]/Q 
add mapped point Co_mem_L/RW0_rdata[1]/q Co_mem_L/RW0_rdata_reg[1]/Q 
add mapped point Co_mem_L/RW0_rdata[6]/q Co_mem_L/RW0_rdata_reg[6]/Q 
add mapped point Co_mem_L/RW0_rdata[4]/q Co_mem_L/RW0_rdata_reg[4]/Q 
add mapped point Co_mem_L/RW0_rdata[0]/q Co_mem_L/RW0_rdata_reg[0]/Q 
add mapped point Co_mem_L/RW0_rdata[3]/q Co_mem_L/RW0_rdata_reg[3]/Q 
add mapped point Co_mem_L/RW0_rdata[2]/q Co_mem_L/RW0_rdata_reg[2]/Q 
add mapped point Co_mem_L/cs_vec[0]/q Co_mem_L/cs_vec_reg[0]/QN 
add mapped point Co_mem_L/cs_vec[1]/q Co_mem_L/cs_vec_reg[1]/QN 
add mapped point Co_mem_R/RW0_rdata[5]/q Co_mem_R/RW0_rdata_reg[5]/Q 
add mapped point Co_mem_R/RW0_rdata[7]/q Co_mem_R/RW0_rdata_reg[7]/Q 
add mapped point Co_mem_R/RW0_rdata[8]/q Co_mem_R/RW0_rdata_reg[8]/Q 
add mapped point Co_mem_R/RW0_rdata[1]/q Co_mem_R/RW0_rdata_reg[1]/Q 
add mapped point Co_mem_R/RW0_rdata[6]/q Co_mem_R/RW0_rdata_reg[6]/Q 
add mapped point Co_mem_R/RW0_rdata[4]/q Co_mem_R/RW0_rdata_reg[4]/Q 
add mapped point Co_mem_R/RW0_rdata[0]/q Co_mem_R/RW0_rdata_reg[0]/Q 
add mapped point Co_mem_R/RW0_rdata[3]/q Co_mem_R/RW0_rdata_reg[3]/Q 
add mapped point Co_mem_R/RW0_rdata[2]/q Co_mem_R/RW0_rdata_reg[2]/Q 
add mapped point Co_mem_R/cs_vec[0]/q Co_mem_R/cs_vec_reg[0]/QN 
add mapped point Co_mem_R/cs_vec[1]/q Co_mem_R/cs_vec_reg[1]/QN 
add mapped point Data_mem_L/count_zero[1]/q Data_mem_L/count_zero_reg[1]/QN 
add mapped point Data_mem_L/count_zero[8]/q Data_mem_L/count_zero_reg[8]/QN 
add mapped point Data_mem_L/count_zero[2]/q Data_mem_L/count_zero_reg[2]/QN 
add mapped point Data_mem_L/count_zero[0]/q Data_mem_L/count_zero_reg[0]/QN 
add mapped point Data_mem_L/count_zero[4]/q Data_mem_L/count_zero_reg[4]/QN 
add mapped point Data_mem_L/count_zero[3]/q Data_mem_L/count_zero_reg[3]/QN 
add mapped point Data_mem_L/count_zero[6]/q Data_mem_L/count_zero_reg[6]/QN 
add mapped point Data_mem_L/count_zero[7]/q Data_mem_L/count_zero_reg[7]/QN 
add mapped point Data_mem_L/count_zero[5]/q Data_mem_L/count_zero_reg[5]/QN 
add mapped point Data_mem_L/allzeros/q Data_mem_L/allzeros_reg/QN 
add mapped point Data_mem_L/count_zero[9]/q Data_mem_L/count_zero_reg[9]/QN 
add mapped point Data_mem_R/count_zero[1]/q Data_mem_R/count_zero_reg[1]/QN 
add mapped point Data_mem_R/count_zero[8]/q Data_mem_R/count_zero_reg[8]/QN 
add mapped point Data_mem_R/count_zero[2]/q Data_mem_R/count_zero_reg[2]/QN 
add mapped point Data_mem_R/count_zero[0]/q Data_mem_R/count_zero_reg[0]/QN 
add mapped point Data_mem_R/count_zero[4]/q Data_mem_R/count_zero_reg[4]/QN 
add mapped point Data_mem_R/count_zero[3]/q Data_mem_R/count_zero_reg[3]/QN 
add mapped point Data_mem_R/count_zero[6]/q Data_mem_R/count_zero_reg[6]/QN 
add mapped point Data_mem_R/count_zero[7]/q Data_mem_R/count_zero_reg[7]/QN 
add mapped point Data_mem_R/count_zero[5]/q Data_mem_R/count_zero_reg[5]/QN 
add mapped point Data_mem_R/allzeros/q Data_mem_R/allzeros_reg/QN 
add mapped point Data_mem_R/count_zero[9]/q Data_mem_R/count_zero_reg[9]/QN 
add mapped point PISOL/OutReady/q PISOL/OutReady_reg/QN 
add mapped point PISOL/OutputSerial/q PISOL/OutputSerial_reg/QN 
add mapped point PISOL/count_bit[0]/q PISOL/count_bit_reg[0]/QN 
add mapped point PISOL/count_bit[1]/q PISOL/count_bit_reg[1]/QN 
add mapped point PISOL/count_bit[2]/q PISOL/count_bit_reg[2]/QN 
add mapped point PISOL/count_bit[3]/q PISOL/count_bit_reg[3]/QN 
add mapped point PISOL/count_bit[4]/q PISOL/count_bit_reg[4]/QN 
add mapped point PISOL/count_bit[5]/q PISOL/count_bit_reg[5]/QN 
add mapped point PISOL/ready_out/q PISOL/ready_out_reg/QN 
add mapped point PISOL/register_dataout[0]/q PISOL/register_dataout_reg[0]/QN 
add mapped point PISOL/register_dataout[1]/q PISOL/register_dataout_reg[1]/QN 
add mapped point PISOL/register_dataout[2]/q PISOL/register_dataout_reg[2]/QN 
add mapped point PISOL/register_dataout[3]/q PISOL/register_dataout_reg[3]/QN 
add mapped point PISOL/register_dataout[4]/q PISOL/register_dataout_reg[4]/QN 
add mapped point PISOL/register_dataout[5]/q PISOL/register_dataout_reg[5]/QN 
add mapped point PISOL/register_dataout[6]/q PISOL/register_dataout_reg[6]/QN 
add mapped point PISOL/register_dataout[7]/q PISOL/register_dataout_reg[7]/QN 
add mapped point PISOL/register_dataout[8]/q PISOL/register_dataout_reg[8]/QN 
add mapped point PISOL/register_dataout[9]/q PISOL/register_dataout_reg[9]/QN 
add mapped point PISOL/register_dataout[10]/q PISOL/register_dataout_reg[10]/QN 
add mapped point PISOL/register_dataout[11]/q PISOL/register_dataout_reg[11]/QN 
add mapped point PISOL/register_dataout[12]/q PISOL/register_dataout_reg[12]/QN 
add mapped point PISOL/register_dataout[13]/q PISOL/register_dataout_reg[13]/QN 
add mapped point PISOL/register_dataout[14]/q PISOL/register_dataout_reg[14]/QN 
add mapped point PISOL/register_dataout[15]/q PISOL/register_dataout_reg[15]/QN 
add mapped point PISOL/register_dataout[16]/q PISOL/register_dataout_reg[16]/QN 
add mapped point PISOL/register_dataout[17]/q PISOL/register_dataout_reg[17]/QN 
add mapped point PISOL/register_dataout[18]/q PISOL/register_dataout_reg[18]/QN 
add mapped point PISOL/register_dataout[19]/q PISOL/register_dataout_reg[19]/QN 
add mapped point PISOL/register_dataout[20]/q PISOL/register_dataout_reg[20]/QN 
add mapped point PISOL/register_dataout[21]/q PISOL/register_dataout_reg[21]/QN 
add mapped point PISOL/register_dataout[22]/q PISOL/register_dataout_reg[22]/QN 
add mapped point PISOL/register_dataout[23]/q PISOL/register_dataout_reg[23]/QN 
add mapped point PISOL/register_dataout[24]/q PISOL/register_dataout_reg[24]/QN 
add mapped point PISOL/register_dataout[25]/q PISOL/register_dataout_reg[25]/QN 
add mapped point PISOL/register_dataout[26]/q PISOL/register_dataout_reg[26]/QN 
add mapped point PISOL/register_dataout[27]/q PISOL/register_dataout_reg[27]/QN 
add mapped point PISOL/register_dataout[28]/q PISOL/register_dataout_reg[28]/QN 
add mapped point PISOL/register_dataout[29]/q PISOL/register_dataout_reg[29]/QN 
add mapped point PISOL/register_dataout[30]/q PISOL/register_dataout_reg[30]/QN 
add mapped point PISOL/register_dataout[31]/q PISOL/register_dataout_reg[31]/QN 
add mapped point PISOL/register_dataout[32]/q PISOL/register_dataout_reg[32]/QN 
add mapped point PISOL/register_dataout[33]/q PISOL/register_dataout_reg[33]/QN 
add mapped point PISOL/register_dataout[34]/q PISOL/register_dataout_reg[34]/QN 
add mapped point PISOL/register_dataout[35]/q PISOL/register_dataout_reg[35]/QN 
add mapped point PISOL/register_dataout[36]/q PISOL/register_dataout_reg[36]/QN 
add mapped point PISOL/register_dataout[37]/q PISOL/register_dataout_reg[37]/QN 
add mapped point PISOL/register_dataout[38]/q PISOL/register_dataout_reg[38]/QN 
add mapped point PISOL/register_dataout[39]/q PISOL/register_dataout_reg[39]/QN 
add mapped point PISOR/OutReady/q PISOR/OutReady_reg/QN 
add mapped point PISOR/OutputSerial/q PISOR/OutputSerial_reg/QN 
add mapped point PISOR/count_bit[0]/q PISOR/count_bit_reg[0]/QN 
add mapped point PISOR/count_bit[1]/q PISOR/count_bit_reg[1]/QN 
add mapped point PISOR/count_bit[2]/q PISOR/count_bit_reg[2]/QN 
add mapped point PISOR/count_bit[3]/q PISOR/count_bit_reg[3]/QN 
add mapped point PISOR/count_bit[4]/q PISOR/count_bit_reg[4]/QN 
add mapped point PISOR/count_bit[5]/q PISOR/count_bit_reg[5]/QN 
add mapped point PISOR/ready_out/q PISOR/ready_out_reg/QN 
add mapped point PISOR/register_dataout[0]/q PISOR/register_dataout_reg[0]/QN 
add mapped point PISOR/register_dataout[1]/q PISOR/register_dataout_reg[1]/QN 
add mapped point PISOR/register_dataout[2]/q PISOR/register_dataout_reg[2]/QN 
add mapped point PISOR/register_dataout[3]/q PISOR/register_dataout_reg[3]/QN 
add mapped point PISOR/register_dataout[4]/q PISOR/register_dataout_reg[4]/QN 
add mapped point PISOR/register_dataout[5]/q PISOR/register_dataout_reg[5]/QN 
add mapped point PISOR/register_dataout[6]/q PISOR/register_dataout_reg[6]/QN 
add mapped point PISOR/register_dataout[7]/q PISOR/register_dataout_reg[7]/QN 
add mapped point PISOR/register_dataout[8]/q PISOR/register_dataout_reg[8]/QN 
add mapped point PISOR/register_dataout[9]/q PISOR/register_dataout_reg[9]/QN 
add mapped point PISOR/register_dataout[10]/q PISOR/register_dataout_reg[10]/QN 
add mapped point PISOR/register_dataout[11]/q PISOR/register_dataout_reg[11]/QN 
add mapped point PISOR/register_dataout[12]/q PISOR/register_dataout_reg[12]/QN 
add mapped point PISOR/register_dataout[13]/q PISOR/register_dataout_reg[13]/QN 
add mapped point PISOR/register_dataout[14]/q PISOR/register_dataout_reg[14]/QN 
add mapped point PISOR/register_dataout[15]/q PISOR/register_dataout_reg[15]/QN 
add mapped point PISOR/register_dataout[16]/q PISOR/register_dataout_reg[16]/QN 
add mapped point PISOR/register_dataout[17]/q PISOR/register_dataout_reg[17]/QN 
add mapped point PISOR/register_dataout[18]/q PISOR/register_dataout_reg[18]/QN 
add mapped point PISOR/register_dataout[19]/q PISOR/register_dataout_reg[19]/QN 
add mapped point PISOR/register_dataout[20]/q PISOR/register_dataout_reg[20]/QN 
add mapped point PISOR/register_dataout[21]/q PISOR/register_dataout_reg[21]/QN 
add mapped point PISOR/register_dataout[22]/q PISOR/register_dataout_reg[22]/QN 
add mapped point PISOR/register_dataout[23]/q PISOR/register_dataout_reg[23]/QN 
add mapped point PISOR/register_dataout[24]/q PISOR/register_dataout_reg[24]/QN 
add mapped point PISOR/register_dataout[25]/q PISOR/register_dataout_reg[25]/QN 
add mapped point PISOR/register_dataout[26]/q PISOR/register_dataout_reg[26]/QN 
add mapped point PISOR/register_dataout[27]/q PISOR/register_dataout_reg[27]/QN 
add mapped point PISOR/register_dataout[28]/q PISOR/register_dataout_reg[28]/QN 
add mapped point PISOR/register_dataout[29]/q PISOR/register_dataout_reg[29]/QN 
add mapped point PISOR/register_dataout[30]/q PISOR/register_dataout_reg[30]/QN 
add mapped point PISOR/register_dataout[31]/q PISOR/register_dataout_reg[31]/QN 
add mapped point PISOR/register_dataout[32]/q PISOR/register_dataout_reg[32]/QN 
add mapped point PISOR/register_dataout[33]/q PISOR/register_dataout_reg[33]/QN 
add mapped point PISOR/register_dataout[34]/q PISOR/register_dataout_reg[34]/QN 
add mapped point PISOR/register_dataout[35]/q PISOR/register_dataout_reg[35]/QN 
add mapped point PISOR/register_dataout[36]/q PISOR/register_dataout_reg[36]/QN 
add mapped point PISOR/register_dataout[37]/q PISOR/register_dataout_reg[37]/QN 
add mapped point PISOR/register_dataout[38]/q PISOR/register_dataout_reg[38]/QN 
add mapped point PISOR/register_dataout[39]/q PISOR/register_dataout_reg[39]/QN 
add mapped point alu_ctrl/clearL/q alu_ctrl/clearL_reg/QN 
add mapped point alu_ctrl/clearR/q alu_ctrl/clearR_reg/QN 
add mapped point alu_ctrl/enable_PISO_L/q alu_ctrl/enable_PISO_L_reg/QN 
add mapped point alu_ctrl/enable_PISO_R/q alu_ctrl/enable_PISO_R_reg/QN 
add mapped point alu_ctrl/inputL_enable/q alu_ctrl/inputL_enable_reg/QN 
add mapped point alu_ctrl/inputR_enable/q alu_ctrl/inputR_enable_reg/QN 
add mapped point alu_ctrl/loadL/q alu_ctrl/loadL_reg/QN 
add mapped point alu_ctrl/loadR/q alu_ctrl/loadR_reg/QN 
add mapped point alu_ctrl/shiftL_en/q alu_ctrl/shiftL_en_reg/QN 
add mapped point alu_ctrl/shiftR_en/q alu_ctrl/shiftR_en_reg/QN 
add mapped point alu_ctrl/addsubL/q alu_ctrl/addsubL_reg/QN 
add mapped point alu_ctrl/addsubR/q alu_ctrl/addsubR_reg/QN 
add mapped point alu_ctrl/coeffL_addr[0]/q alu_ctrl/coeffL_addr_reg[0]/QN 
add mapped point alu_ctrl/coeffL_addr[1]/q alu_ctrl/coeffL_addr_reg[1]/QN 
add mapped point alu_ctrl/coeffL_addr[2]/q alu_ctrl/coeffL_addr_reg[2]/QN 
add mapped point alu_ctrl/coeffL_addr[3]/q alu_ctrl/coeffL_addr_reg[3]/QN 
add mapped point alu_ctrl/coeffL_addr[4]/q alu_ctrl/coeffL_addr_reg[4]/QN 
add mapped point alu_ctrl/coeffL_addr[5]/q alu_ctrl/coeffL_addr_reg[5]/QN 
add mapped point alu_ctrl/coeffL_addr[6]/q alu_ctrl/coeffL_addr_reg[6]/QN 
add mapped point alu_ctrl/coeffL_addr[7]/q alu_ctrl/coeffL_addr_reg[7]/QN 
add mapped point alu_ctrl/coeffL_addr[8]/q alu_ctrl/coeffL_addr_reg[8]/QN 
add mapped point alu_ctrl/coeffL_enable/q alu_ctrl/coeffL_enable_reg/QN 
add mapped point alu_ctrl/coeffR_addr[0]/q alu_ctrl/coeffR_addr_reg[0]/QN 
add mapped point alu_ctrl/coeffR_addr[1]/q alu_ctrl/coeffR_addr_reg[1]/QN 
add mapped point alu_ctrl/coeffR_addr[2]/q alu_ctrl/coeffR_addr_reg[2]/QN 
add mapped point alu_ctrl/coeffR_addr[3]/q alu_ctrl/coeffR_addr_reg[3]/QN 
add mapped point alu_ctrl/coeffR_addr[4]/q alu_ctrl/coeffR_addr_reg[4]/QN 
add mapped point alu_ctrl/coeffR_addr[5]/q alu_ctrl/coeffR_addr_reg[5]/QN 
add mapped point alu_ctrl/coeffR_addr[6]/q alu_ctrl/coeffR_addr_reg[6]/QN 
add mapped point alu_ctrl/coeffR_addr[7]/q alu_ctrl/coeffR_addr_reg[7]/QN 
add mapped point alu_ctrl/coeffR_addr[8]/q alu_ctrl/coeffR_addr_reg[8]/QN 
add mapped point alu_ctrl/coeffR_enable/q alu_ctrl/coeffR_enable_reg/QN 
add mapped point alu_ctrl/inputL_addr[0]/q alu_ctrl/inputL_addr_reg[0]/QN 
add mapped point alu_ctrl/inputL_addr[1]/q alu_ctrl/inputL_addr_reg[1]/QN 
add mapped point alu_ctrl/inputL_addr[2]/q alu_ctrl/inputL_addr_reg[2]/QN 
add mapped point alu_ctrl/inputL_addr[3]/q alu_ctrl/inputL_addr_reg[3]/QN 
add mapped point alu_ctrl/inputL_addr[4]/q alu_ctrl/inputL_addr_reg[4]/QN 
add mapped point alu_ctrl/inputL_addr[5]/q alu_ctrl/inputL_addr_reg[5]/QN 
add mapped point alu_ctrl/inputL_addr[6]/q alu_ctrl/inputL_addr_reg[6]/QN 
add mapped point alu_ctrl/inputL_addr[7]/q alu_ctrl/inputL_addr_reg[7]/QN 
add mapped point alu_ctrl/inputR_addr[0]/q alu_ctrl/inputR_addr_reg[0]/QN 
add mapped point alu_ctrl/inputR_addr[1]/q alu_ctrl/inputR_addr_reg[1]/QN 
add mapped point alu_ctrl/inputR_addr[2]/q alu_ctrl/inputR_addr_reg[2]/QN 
add mapped point alu_ctrl/inputR_addr[3]/q alu_ctrl/inputR_addr_reg[3]/QN 
add mapped point alu_ctrl/inputR_addr[4]/q alu_ctrl/inputR_addr_reg[4]/QN 
add mapped point alu_ctrl/inputR_addr[5]/q alu_ctrl/inputR_addr_reg[5]/QN 
add mapped point alu_ctrl/inputR_addr[6]/q alu_ctrl/inputR_addr_reg[6]/QN 
add mapped point alu_ctrl/inputR_addr[7]/q alu_ctrl/inputR_addr_reg[7]/QN 
add mapped point alu_ctrl/kL[0]/q alu_ctrl/kL_reg[0]/QN 
add mapped point alu_ctrl/kL[1]/q alu_ctrl/kL_reg[1]/QN 
add mapped point alu_ctrl/kL[2]/q alu_ctrl/kL_reg[2]/QN 
add mapped point alu_ctrl/kL[3]/q alu_ctrl/kL_reg[3]/QN 
add mapped point alu_ctrl/kL[4]/q alu_ctrl/kL_reg[4]/QN 
add mapped point alu_ctrl/kL[5]/q alu_ctrl/kL_reg[5]/QN 
add mapped point alu_ctrl/kL[6]/q alu_ctrl/kL_reg[6]/QN 
add mapped point alu_ctrl/kL[7]/q alu_ctrl/kL_reg[7]/QN 
add mapped point alu_ctrl/kR[0]/q alu_ctrl/kR_reg[0]/QN 
add mapped point alu_ctrl/kR[1]/q alu_ctrl/kR_reg[1]/QN 
add mapped point alu_ctrl/kR[2]/q alu_ctrl/kR_reg[2]/QN 
add mapped point alu_ctrl/kR[3]/q alu_ctrl/kR_reg[3]/QN 
add mapped point alu_ctrl/kR[4]/q alu_ctrl/kR_reg[4]/QN 
add mapped point alu_ctrl/kR[5]/q alu_ctrl/kR_reg[5]/QN 
add mapped point alu_ctrl/kR[6]/q alu_ctrl/kR_reg[6]/QN 
add mapped point alu_ctrl/kR[7]/q alu_ctrl/kR_reg[7]/QN 
add mapped point alu_ctrl/memL_overflow/q alu_ctrl/memL_overflow_reg/QN 
add mapped point alu_ctrl/memR_overflow/q alu_ctrl/memR_overflow_reg/QN 
add mapped point alu_ctrl/next_stateL[0]/q alu_ctrl/next_stateL_reg[0]/QN 
add mapped point alu_ctrl/next_stateL[1]/q alu_ctrl/next_stateL_reg[1]/QN 
add mapped point alu_ctrl/next_stateR[0]/q alu_ctrl/next_stateR_reg[0]/QN 
add mapped point alu_ctrl/outL/q alu_ctrl/outL_reg/QN 
add mapped point alu_ctrl/outR/q alu_ctrl/outR_reg/QN 
add mapped point alu_ctrl/rjL_addr[0]/q alu_ctrl/rjL_addr_reg[0]/QN 
add mapped point alu_ctrl/rjL_addr[1]/q alu_ctrl/rjL_addr_reg[1]/QN 
add mapped point alu_ctrl/rjL_addr[2]/q alu_ctrl/rjL_addr_reg[2]/QN 
add mapped point alu_ctrl/rjL_addr[3]/q alu_ctrl/rjL_addr_reg[3]/QN 
add mapped point alu_ctrl/rjR_addr[0]/q alu_ctrl/rjR_addr_reg[0]/QN 
add mapped point alu_ctrl/rjR_addr[1]/q alu_ctrl/rjR_addr_reg[1]/QN 
add mapped point alu_ctrl/rjR_addr[2]/q alu_ctrl/rjR_addr_reg[2]/QN 
add mapped point alu_ctrl/rjR_addr[3]/q alu_ctrl/rjR_addr_reg[3]/QN 
add mapped point alu_ctrl/start_workL/q alu_ctrl/start_workL_reg/QN 
add mapped point alu_ctrl/start_workR/q alu_ctrl/start_workR_reg/QN 
add mapped point alu_ctrl/work_statusL/q alu_ctrl/work_statusL_reg/QN 
add mapped point alu_ctrl/work_statusR/q alu_ctrl/work_statusR_reg/QN 
add mapped point alu_ctrl/xcntL[0]/q alu_ctrl/xcntL_reg[0]/QN 
add mapped point alu_ctrl/xcntL[1]/q alu_ctrl/xcntL_reg[1]/QN 
add mapped point alu_ctrl/xcntL[2]/q alu_ctrl/xcntL_reg[2]/QN 
add mapped point alu_ctrl/xcntL[3]/q alu_ctrl/xcntL_reg[3]/QN 
add mapped point alu_ctrl/xcntL[4]/q alu_ctrl/xcntL_reg[4]/QN 
add mapped point alu_ctrl/xcntL[5]/q alu_ctrl/xcntL_reg[5]/QN 
add mapped point alu_ctrl/xcntL[6]/q alu_ctrl/xcntL_reg[6]/QN 
add mapped point alu_ctrl/xcntL[7]/q alu_ctrl/xcntL_reg[7]/QN 
add mapped point alu_ctrl/xcntR[0]/q alu_ctrl/xcntR_reg[0]/QN 
add mapped point alu_ctrl/xcntR[1]/q alu_ctrl/xcntR_reg[1]/QN 
add mapped point alu_ctrl/xcntR[2]/q alu_ctrl/xcntR_reg[2]/QN 
add mapped point alu_ctrl/xcntR[3]/q alu_ctrl/xcntR_reg[3]/QN 
add mapped point alu_ctrl/xcntR[4]/q alu_ctrl/xcntR_reg[4]/QN 
add mapped point alu_ctrl/xcntR[5]/q alu_ctrl/xcntR_reg[5]/QN 
add mapped point alu_ctrl/xcntR[6]/q alu_ctrl/xcntR_reg[6]/QN 
add mapped point alu_ctrl/xcntR[7]/q alu_ctrl/xcntR_reg[7]/QN 
add mapped point main_ctrl/Clear/q main_ctrl/Clear_reg/QN 
add mapped point main_ctrl/Coefficient_Read_Address[0]/q main_ctrl/Coefficient_Read_Address_reg[0]/QN 
add mapped point main_ctrl/Coefficient_Read_Address[1]/q main_ctrl/Coefficient_Read_Address_reg[1]/QN 
add mapped point main_ctrl/Coefficient_Read_Address[2]/q main_ctrl/Coefficient_Read_Address_reg[2]/QN 
add mapped point main_ctrl/Coefficient_Read_Address[3]/q main_ctrl/Coefficient_Read_Address_reg[3]/QN 
add mapped point main_ctrl/Coefficient_Read_Address[4]/q main_ctrl/Coefficient_Read_Address_reg[4]/QN 
add mapped point main_ctrl/Coefficient_Read_Address[5]/q main_ctrl/Coefficient_Read_Address_reg[5]/QN 
add mapped point main_ctrl/Coefficient_Read_Address[6]/q main_ctrl/Coefficient_Read_Address_reg[6]/QN 
add mapped point main_ctrl/Coefficient_Read_Address[7]/q main_ctrl/Coefficient_Read_Address_reg[7]/QN 
add mapped point main_ctrl/Coefficient_Read_Address[8]/q main_ctrl/Coefficient_Read_Address_reg[8]/QN 
add mapped point main_ctrl/Coefficient_Read_Enable/q main_ctrl/Coefficient_Read_Enable_reg/QN 
add mapped point main_ctrl/Data_Read_Enable/q main_ctrl/Data_Read_Enable_reg/QN 
add mapped point main_ctrl/InReady/q main_ctrl/InReady_reg/QN 
add mapped point main_ctrl/Input_Read_Address[0]/q main_ctrl/Input_Read_Address_reg[0]/QN 
add mapped point main_ctrl/Input_Read_Address[1]/q main_ctrl/Input_Read_Address_reg[1]/QN 
add mapped point main_ctrl/Input_Read_Address[2]/q main_ctrl/Input_Read_Address_reg[2]/QN 
add mapped point main_ctrl/Input_Read_Address[3]/q main_ctrl/Input_Read_Address_reg[3]/QN 
add mapped point main_ctrl/Input_Read_Address[4]/q main_ctrl/Input_Read_Address_reg[4]/QN 
add mapped point main_ctrl/Input_Read_Address[5]/q main_ctrl/Input_Read_Address_reg[5]/QN 
add mapped point main_ctrl/Input_Read_Address[6]/q main_ctrl/Input_Read_Address_reg[6]/QN 
add mapped point main_ctrl/Input_Read_Address[7]/q main_ctrl/Input_Read_Address_reg[7]/QN 
add mapped point main_ctrl/Rj_Read_Address[0]/q main_ctrl/Rj_Read_Address_reg[0]/QN 
add mapped point main_ctrl/Rj_Read_Address[1]/q main_ctrl/Rj_Read_Address_reg[1]/QN 
add mapped point main_ctrl/Rj_Read_Address[2]/q main_ctrl/Rj_Read_Address_reg[2]/QN 
add mapped point main_ctrl/Rj_Read_Address[3]/q main_ctrl/Rj_Read_Address_reg[3]/QN 
add mapped point main_ctrl/Rj_Read_Enable/q main_ctrl/Rj_Read_Enable_reg/QN 
add mapped point main_ctrl/count_coeff[0]/q main_ctrl/count_coeff_reg[0]/QN 
add mapped point main_ctrl/count_coeff[1]/q main_ctrl/count_coeff_reg[1]/QN 
add mapped point main_ctrl/count_coeff[2]/q main_ctrl/count_coeff_reg[2]/QN 
add mapped point main_ctrl/count_coeff[3]/q main_ctrl/count_coeff_reg[3]/QN 
add mapped point main_ctrl/count_coeff[4]/q main_ctrl/count_coeff_reg[4]/QN 
add mapped point main_ctrl/count_coeff[5]/q main_ctrl/count_coeff_reg[5]/QN 
add mapped point main_ctrl/count_coeff[6]/q main_ctrl/count_coeff_reg[6]/QN 
add mapped point main_ctrl/count_coeff[7]/q main_ctrl/count_coeff_reg[7]/QN 
add mapped point main_ctrl/count_coeff[8]/q main_ctrl/count_coeff_reg[8]/QN 
add mapped point main_ctrl/count_coeff[9]/q main_ctrl/count_coeff_reg[9]/QN 
add mapped point main_ctrl/count_data[0]/q main_ctrl/count_data_reg[0]/QN 
add mapped point main_ctrl/count_data[1]/q main_ctrl/count_data_reg[1]/QN 
add mapped point main_ctrl/count_data[2]/q main_ctrl/count_data_reg[2]/QN 
add mapped point main_ctrl/count_data[3]/q main_ctrl/count_data_reg[3]/QN 
add mapped point main_ctrl/count_data[4]/q main_ctrl/count_data_reg[4]/QN 
add mapped point main_ctrl/count_data[5]/q main_ctrl/count_data_reg[5]/QN 
add mapped point main_ctrl/count_data[6]/q main_ctrl/count_data_reg[6]/QN 
add mapped point main_ctrl/count_data[7]/q main_ctrl/count_data_reg[7]/QN 
add mapped point main_ctrl/count_rj[0]/q main_ctrl/count_rj_reg[0]/QN 
add mapped point main_ctrl/count_rj[1]/q main_ctrl/count_rj_reg[1]/QN 
add mapped point main_ctrl/count_rj[2]/q main_ctrl/count_rj_reg[2]/QN 
add mapped point main_ctrl/count_rj[3]/q main_ctrl/count_rj_reg[3]/QN 
add mapped point main_ctrl/count_rj[4]/q main_ctrl/count_rj_reg[4]/QN 
add mapped point main_ctrl/sleep_flag/q main_ctrl/sleep_flag_reg/QN 
add mapped point main_ctrl/state_next[0]/q main_ctrl/state_next_reg[0]/QN 
add mapped point main_ctrl/state_next[1]/q main_ctrl/state_next_reg[1]/QN 
add mapped point main_ctrl/state_next[2]/q main_ctrl/state_next_reg[2]/QN 
add mapped point main_ctrl/state_next[3]/q main_ctrl/state_next_reg[3]/QN 
add mapped point main_ctrl/state_present[0]/q main_ctrl/state_present_reg[0]/QN 
add mapped point main_ctrl/state_present[1]/q main_ctrl/state_present_reg[1]/QN 
add mapped point main_ctrl/state_present[2]/q main_ctrl/state_present_reg[2]/QN 
add mapped point main_ctrl/state_present[3]/q main_ctrl/state_present_reg[3]/QN 
add mapped point main_ctrl/tk/q main_ctrl/tk_reg/QN 
add mapped point pipo/input_ready/q pipo/input_ready_reg/QN 
add mapped point pipo/bitpos[0]/q pipo/bitpos_reg[0]/QN 
add mapped point pipo/bitpos[1]/q pipo/bitpos_reg[1]/QN 
add mapped point pipo/bitpos[2]/q pipo/bitpos_reg[2]/QN 
add mapped point pipo/bitpos[3]/q pipo/bitpos_reg[3]/QN 
add mapped point pipo/continueFrame/q pipo/continueFrame_reg/QN 
add mapped point pipo/dataL[0]/q pipo/dataL_reg[0]/QN 
add mapped point pipo/dataL[1]/q pipo/dataL_reg[1]/QN 
add mapped point pipo/dataL[2]/q pipo/dataL_reg[2]/QN 
add mapped point pipo/dataL[3]/q pipo/dataL_reg[3]/QN 
add mapped point pipo/dataL[4]/q pipo/dataL_reg[4]/QN 
add mapped point pipo/dataL[5]/q pipo/dataL_reg[5]/QN 
add mapped point pipo/dataL[6]/q pipo/dataL_reg[6]/QN 
add mapped point pipo/dataL[7]/q pipo/dataL_reg[7]/QN 
add mapped point pipo/dataL[8]/q pipo/dataL_reg[8]/QN 
add mapped point pipo/dataL[9]/q pipo/dataL_reg[9]/QN 
add mapped point pipo/dataL[10]/q pipo/dataL_reg[10]/QN 
add mapped point pipo/dataL[11]/q pipo/dataL_reg[11]/QN 
add mapped point pipo/dataL[12]/q pipo/dataL_reg[12]/QN 
add mapped point pipo/dataL[13]/q pipo/dataL_reg[13]/QN 
add mapped point pipo/dataL[14]/q pipo/dataL_reg[14]/QN 
add mapped point pipo/dataL[15]/q pipo/dataL_reg[15]/QN 
add mapped point pipo/dataR[0]/q pipo/dataR_reg[0]/QN 
add mapped point pipo/dataR[1]/q pipo/dataR_reg[1]/QN 
add mapped point pipo/dataR[2]/q pipo/dataR_reg[2]/QN 
add mapped point pipo/dataR[3]/q pipo/dataR_reg[3]/QN 
add mapped point pipo/dataR[4]/q pipo/dataR_reg[4]/QN 
add mapped point pipo/dataR[5]/q pipo/dataR_reg[5]/QN 
add mapped point pipo/dataR[6]/q pipo/dataR_reg[6]/QN 
add mapped point pipo/dataR[7]/q pipo/dataR_reg[7]/QN 
add mapped point pipo/dataR[8]/q pipo/dataR_reg[8]/QN 
add mapped point pipo/dataR[9]/q pipo/dataR_reg[9]/QN 
add mapped point pipo/dataR[10]/q pipo/dataR_reg[10]/QN 
add mapped point pipo/dataR[11]/q pipo/dataR_reg[11]/QN 
add mapped point pipo/dataR[12]/q pipo/dataR_reg[12]/QN 
add mapped point pipo/dataR[13]/q pipo/dataR_reg[13]/QN 
add mapped point pipo/dataR[14]/q pipo/dataR_reg[14]/QN 
add mapped point pipo/dataR[15]/q pipo/dataR_reg[15]/QN 
add mapped point shiftL/tempreg[0]/q shiftL/tempreg_reg[0]/QN 
add mapped point shiftL/tempreg[1]/q shiftL/tempreg_reg[1]/QN 
add mapped point shiftL/tempreg[2]/q shiftL/tempreg_reg[2]/QN 
add mapped point shiftL/tempreg[3]/q shiftL/tempreg_reg[3]/QN 
add mapped point shiftL/tempreg[4]/q shiftL/tempreg_reg[4]/QN 
add mapped point shiftL/tempreg[5]/q shiftL/tempreg_reg[5]/QN 
add mapped point shiftL/tempreg[6]/q shiftL/tempreg_reg[6]/QN 
add mapped point shiftL/tempreg[7]/q shiftL/tempreg_reg[7]/QN 
add mapped point shiftL/tempreg[8]/q shiftL/tempreg_reg[8]/QN 
add mapped point shiftL/tempreg[9]/q shiftL/tempreg_reg[9]/QN 
add mapped point shiftL/tempreg[10]/q shiftL/tempreg_reg[10]/QN 
add mapped point shiftL/tempreg[11]/q shiftL/tempreg_reg[11]/QN 
add mapped point shiftL/tempreg[12]/q shiftL/tempreg_reg[12]/QN 
add mapped point shiftL/tempreg[13]/q shiftL/tempreg_reg[13]/QN 
add mapped point shiftL/tempreg[14]/q shiftL/tempreg_reg[14]/QN 
add mapped point shiftL/tempreg[15]/q shiftL/tempreg_reg[15]/QN 
add mapped point shiftL/tempreg[16]/q shiftL/tempreg_reg[16]/QN 
add mapped point shiftL/tempreg[17]/q shiftL/tempreg_reg[17]/QN 
add mapped point shiftL/tempreg[18]/q shiftL/tempreg_reg[18]/QN 
add mapped point shiftL/tempreg[19]/q shiftL/tempreg_reg[19]/QN 
add mapped point shiftL/tempreg[20]/q shiftL/tempreg_reg[20]/QN 
add mapped point shiftL/tempreg[21]/q shiftL/tempreg_reg[21]/QN 
add mapped point shiftL/tempreg[22]/q shiftL/tempreg_reg[22]/QN 
add mapped point shiftL/tempreg[23]/q shiftL/tempreg_reg[23]/QN 
add mapped point shiftL/tempreg[24]/q shiftL/tempreg_reg[24]/QN 
add mapped point shiftL/tempreg[25]/q shiftL/tempreg_reg[25]/QN 
add mapped point shiftL/tempreg[26]/q shiftL/tempreg_reg[26]/QN 
add mapped point shiftL/tempreg[27]/q shiftL/tempreg_reg[27]/QN 
add mapped point shiftL/tempreg[28]/q shiftL/tempreg_reg[28]/QN 
add mapped point shiftL/tempreg[29]/q shiftL/tempreg_reg[29]/QN 
add mapped point shiftL/tempreg[30]/q shiftL/tempreg_reg[30]/QN 
add mapped point shiftL/tempreg[31]/q shiftL/tempreg_reg[31]/QN 
add mapped point shiftL/tempreg[32]/q shiftL/tempreg_reg[32]/QN 
add mapped point shiftL/tempreg[33]/q shiftL/tempreg_reg[33]/QN 
add mapped point shiftL/tempreg[34]/q shiftL/tempreg_reg[34]/QN 
add mapped point shiftL/tempreg[35]/q shiftL/tempreg_reg[35]/QN 
add mapped point shiftL/tempreg[36]/q shiftL/tempreg_reg[36]/QN 
add mapped point shiftL/tempreg[37]/q shiftL/tempreg_reg[37]/QN 
add mapped point shiftL/tempreg[38]/q shiftL/tempreg_reg[38]/QN 
add mapped point shiftL/tempreg[39]/q shiftL/tempreg_reg[39]/QN 
add mapped point shiftR/tempreg[0]/q shiftR/tempreg_reg[0]/QN 
add mapped point shiftR/tempreg[1]/q shiftR/tempreg_reg[1]/QN 
add mapped point shiftR/tempreg[2]/q shiftR/tempreg_reg[2]/QN 
add mapped point shiftR/tempreg[3]/q shiftR/tempreg_reg[3]/QN 
add mapped point shiftR/tempreg[4]/q shiftR/tempreg_reg[4]/QN 
add mapped point shiftR/tempreg[5]/q shiftR/tempreg_reg[5]/QN 
add mapped point shiftR/tempreg[6]/q shiftR/tempreg_reg[6]/QN 
add mapped point shiftR/tempreg[7]/q shiftR/tempreg_reg[7]/QN 
add mapped point shiftR/tempreg[8]/q shiftR/tempreg_reg[8]/QN 
add mapped point shiftR/tempreg[9]/q shiftR/tempreg_reg[9]/QN 
add mapped point shiftR/tempreg[10]/q shiftR/tempreg_reg[10]/QN 
add mapped point shiftR/tempreg[11]/q shiftR/tempreg_reg[11]/QN 
add mapped point shiftR/tempreg[12]/q shiftR/tempreg_reg[12]/QN 
add mapped point shiftR/tempreg[13]/q shiftR/tempreg_reg[13]/QN 
add mapped point shiftR/tempreg[14]/q shiftR/tempreg_reg[14]/QN 
add mapped point shiftR/tempreg[15]/q shiftR/tempreg_reg[15]/QN 
add mapped point shiftR/tempreg[16]/q shiftR/tempreg_reg[16]/QN 
add mapped point shiftR/tempreg[17]/q shiftR/tempreg_reg[17]/QN 
add mapped point shiftR/tempreg[18]/q shiftR/tempreg_reg[18]/QN 
add mapped point shiftR/tempreg[19]/q shiftR/tempreg_reg[19]/QN 
add mapped point shiftR/tempreg[20]/q shiftR/tempreg_reg[20]/QN 
add mapped point shiftR/tempreg[21]/q shiftR/tempreg_reg[21]/QN 
add mapped point shiftR/tempreg[22]/q shiftR/tempreg_reg[22]/QN 
add mapped point shiftR/tempreg[23]/q shiftR/tempreg_reg[23]/QN 
add mapped point shiftR/tempreg[24]/q shiftR/tempreg_reg[24]/QN 
add mapped point shiftR/tempreg[25]/q shiftR/tempreg_reg[25]/QN 
add mapped point shiftR/tempreg[26]/q shiftR/tempreg_reg[26]/QN 
add mapped point shiftR/tempreg[27]/q shiftR/tempreg_reg[27]/QN 
add mapped point shiftR/tempreg[28]/q shiftR/tempreg_reg[28]/QN 
add mapped point shiftR/tempreg[29]/q shiftR/tempreg_reg[29]/QN 
add mapped point shiftR/tempreg[30]/q shiftR/tempreg_reg[30]/QN 
add mapped point shiftR/tempreg[31]/q shiftR/tempreg_reg[31]/QN 
add mapped point shiftR/tempreg[32]/q shiftR/tempreg_reg[32]/QN 
add mapped point shiftR/tempreg[33]/q shiftR/tempreg_reg[33]/QN 
add mapped point shiftR/tempreg[34]/q shiftR/tempreg_reg[34]/QN 
add mapped point shiftR/tempreg[35]/q shiftR/tempreg_reg[35]/QN 
add mapped point shiftR/tempreg[36]/q shiftR/tempreg_reg[36]/QN 
add mapped point shiftR/tempreg[37]/q shiftR/tempreg_reg[37]/QN 
add mapped point shiftR/tempreg[38]/q shiftR/tempreg_reg[38]/QN 
add mapped point shiftR/tempreg[39]/q shiftR/tempreg_reg[39]/QN 



//Black Boxes
add mapped point Co_mem_L/mem_0_0 Co_mem_L/mem_0_0
add mapped point Co_mem_L/mem_0_1 Co_mem_L/mem_0_1
add mapped point Co_mem_L/mem_0_2 Co_mem_L/mem_0_2
add mapped point Co_mem_L/mem_0_3 Co_mem_L/mem_0_3
add mapped point Co_mem_R/mem_0_0 Co_mem_R/mem_0_0
add mapped point Co_mem_R/mem_0_1 Co_mem_R/mem_0_1
add mapped point Co_mem_R/mem_0_2 Co_mem_R/mem_0_2
add mapped point Co_mem_R/mem_0_3 Co_mem_R/mem_0_3
add mapped point Data_mem_L/mem_0_0 Data_mem_L/mem_0_0
add mapped point Data_mem_L/mem_0_1 Data_mem_L/mem_0_1
add mapped point Data_mem_R/mem_0_0 Data_mem_R/mem_0_0
add mapped point Data_mem_R/mem_0_1 Data_mem_R/mem_0_1
add mapped point R_mem_L/mem_0_0 R_mem_L/mem_0_0
add mapped point R_mem_R/mem_0_0 R_mem_R/mem_0_0



//Empty Modules as Blackboxes
