set_clock_latency -source -early -min -rise  -61.3725 [get_ports {Dclk}] -clock Dclk 
set_clock_latency -source -early -min -fall  -64.8921 [get_ports {Dclk}] -clock Dclk 
set_clock_latency -source -early -max -rise  -61.3725 [get_ports {Dclk}] -clock Dclk 
set_clock_latency -source -early -max -fall  -64.8921 [get_ports {Dclk}] -clock Dclk 
set_clock_latency -source -late -min -rise  -61.3725 [get_ports {Dclk}] -clock Dclk 
set_clock_latency -source -late -min -fall  -64.8921 [get_ports {Dclk}] -clock Dclk 
set_clock_latency -source -late -max -rise  -61.3725 [get_ports {Dclk}] -clock Dclk 
set_clock_latency -source -late -max -fall  -64.8921 [get_ports {Dclk}] -clock Dclk 
set_clock_latency -source -early -min -rise  -126.739 [get_ports {Sclk}] -clock Sclk 
set_clock_latency -source -early -min -fall  -139.14 [get_ports {Sclk}] -clock Sclk 
set_clock_latency -source -early -max -rise  -126.739 [get_ports {Sclk}] -clock Sclk 
set_clock_latency -source -early -max -fall  -139.14 [get_ports {Sclk}] -clock Sclk 
set_clock_latency -source -late -min -rise  -126.739 [get_ports {Sclk}] -clock Sclk 
set_clock_latency -source -late -min -fall  -139.14 [get_ports {Sclk}] -clock Sclk 
set_clock_latency -source -late -max -rise  -126.739 [get_ports {Sclk}] -clock Sclk 
set_clock_latency -source -late -max -fall  -139.14 [get_ports {Sclk}] -clock Sclk 
