set_db port:MSDAP/Dclk .original_name {Dclk}
set_db port:MSDAP/Sclk .original_name {Sclk}
set_db port:MSDAP/Reset_n .original_name {Reset_n}
set_db port:MSDAP/Frame .original_name {Frame}
set_db port:MSDAP/Start .original_name {Start}
set_db {port:MSDAP/InputL[15]} .original_name {InputL[15]}
set_db {port:MSDAP/InputL[14]} .original_name {InputL[14]}
set_db {port:MSDAP/InputL[13]} .original_name {InputL[13]}
set_db {port:MSDAP/InputL[12]} .original_name {InputL[12]}
set_db {port:MSDAP/InputL[11]} .original_name {InputL[11]}
set_db {port:MSDAP/InputL[10]} .original_name {InputL[10]}
set_db {port:MSDAP/InputL[9]} .original_name {InputL[9]}
set_db {port:MSDAP/InputL[8]} .original_name {InputL[8]}
set_db {port:MSDAP/InputL[7]} .original_name {InputL[7]}
set_db {port:MSDAP/InputL[6]} .original_name {InputL[6]}
set_db {port:MSDAP/InputL[5]} .original_name {InputL[5]}
set_db {port:MSDAP/InputL[4]} .original_name {InputL[4]}
set_db {port:MSDAP/InputL[3]} .original_name {InputL[3]}
set_db {port:MSDAP/InputL[2]} .original_name {InputL[2]}
set_db {port:MSDAP/InputL[1]} .original_name {InputL[1]}
set_db {port:MSDAP/InputL[0]} .original_name {InputL[0]}
set_db {port:MSDAP/InputR[15]} .original_name {InputR[15]}
set_db {port:MSDAP/InputR[14]} .original_name {InputR[14]}
set_db {port:MSDAP/InputR[13]} .original_name {InputR[13]}
set_db {port:MSDAP/InputR[12]} .original_name {InputR[12]}
set_db {port:MSDAP/InputR[11]} .original_name {InputR[11]}
set_db {port:MSDAP/InputR[10]} .original_name {InputR[10]}
set_db {port:MSDAP/InputR[9]} .original_name {InputR[9]}
set_db {port:MSDAP/InputR[8]} .original_name {InputR[8]}
set_db {port:MSDAP/InputR[7]} .original_name {InputR[7]}
set_db {port:MSDAP/InputR[6]} .original_name {InputR[6]}
set_db {port:MSDAP/InputR[5]} .original_name {InputR[5]}
set_db {port:MSDAP/InputR[4]} .original_name {InputR[4]}
set_db {port:MSDAP/InputR[3]} .original_name {InputR[3]}
set_db {port:MSDAP/InputR[2]} .original_name {InputR[2]}
set_db {port:MSDAP/InputR[1]} .original_name {InputR[1]}
set_db {port:MSDAP/InputR[0]} .original_name {InputR[0]}
set_db port:MSDAP/InReady .original_name {InReady}
set_db port:MSDAP/OutReady .original_name {OutReady}
set_db port:MSDAP/OutputL .original_name {OutputL}
set_db port:MSDAP/OutputR .original_name {OutputR}



set_db {pin:MSDAP/Co_mem_L/RW0_rdata_reg[5]/Q} .original_name {Co_mem_L/RW0_rdata[5]/q}
set_db {pin:MSDAP/Co_mem_L/RW0_rdata_reg[7]/Q} .original_name {Co_mem_L/RW0_rdata[7]/q}
set_db {pin:MSDAP/Co_mem_L/RW0_rdata_reg[8]/Q} .original_name {Co_mem_L/RW0_rdata[8]/q}
set_db {pin:MSDAP/Co_mem_L/RW0_rdata_reg[1]/Q} .original_name {Co_mem_L/RW0_rdata[1]/q}
set_db {pin:MSDAP/Co_mem_L/RW0_rdata_reg[6]/Q} .original_name {Co_mem_L/RW0_rdata[6]/q}
set_db {pin:MSDAP/Co_mem_L/RW0_rdata_reg[4]/Q} .original_name {Co_mem_L/RW0_rdata[4]/q}
set_db {pin:MSDAP/Co_mem_L/RW0_rdata_reg[0]/Q} .original_name {Co_mem_L/RW0_rdata[0]/q}
set_db {pin:MSDAP/Co_mem_L/RW0_rdata_reg[3]/Q} .original_name {Co_mem_L/RW0_rdata[3]/q}
set_db {pin:MSDAP/Co_mem_L/RW0_rdata_reg[2]/Q} .original_name {Co_mem_L/RW0_rdata[2]/q}
set_db {pin:MSDAP/Co_mem_L/cs_vec_reg[0]/QN} .original_name {Co_mem_L/cs_vec[0]/q}
set_db {pin:MSDAP/Co_mem_L/cs_vec_reg[1]/QN} .original_name {Co_mem_L/cs_vec[1]/q}
set_db {pin:MSDAP/Co_mem_R/RW0_rdata_reg[5]/Q} .original_name {Co_mem_R/RW0_rdata[5]/q}
set_db {pin:MSDAP/Co_mem_R/RW0_rdata_reg[7]/Q} .original_name {Co_mem_R/RW0_rdata[7]/q}
set_db {pin:MSDAP/Co_mem_R/RW0_rdata_reg[8]/Q} .original_name {Co_mem_R/RW0_rdata[8]/q}
set_db {pin:MSDAP/Co_mem_R/RW0_rdata_reg[1]/Q} .original_name {Co_mem_R/RW0_rdata[1]/q}
set_db {pin:MSDAP/Co_mem_R/RW0_rdata_reg[6]/Q} .original_name {Co_mem_R/RW0_rdata[6]/q}
set_db {pin:MSDAP/Co_mem_R/RW0_rdata_reg[4]/Q} .original_name {Co_mem_R/RW0_rdata[4]/q}
set_db {pin:MSDAP/Co_mem_R/RW0_rdata_reg[0]/Q} .original_name {Co_mem_R/RW0_rdata[0]/q}
set_db {pin:MSDAP/Co_mem_R/RW0_rdata_reg[3]/Q} .original_name {Co_mem_R/RW0_rdata[3]/q}
set_db {pin:MSDAP/Co_mem_R/RW0_rdata_reg[2]/Q} .original_name {Co_mem_R/RW0_rdata[2]/q}
set_db {pin:MSDAP/Co_mem_R/cs_vec_reg[0]/QN} .original_name {Co_mem_R/cs_vec[0]/q}
set_db {pin:MSDAP/Co_mem_R/cs_vec_reg[1]/QN} .original_name {Co_mem_R/cs_vec[1]/q}
set_db {pin:MSDAP/Data_mem_L/count_zero_reg[1]/QN} .original_name {Data_mem_L/count_zero[1]/q}
set_db {pin:MSDAP/Data_mem_L/count_zero_reg[8]/QN} .original_name {Data_mem_L/count_zero[8]/q}
set_db {pin:MSDAP/Data_mem_L/count_zero_reg[2]/QN} .original_name {Data_mem_L/count_zero[2]/q}
set_db {pin:MSDAP/Data_mem_L/count_zero_reg[0]/QN} .original_name {Data_mem_L/count_zero[0]/q}
set_db {pin:MSDAP/Data_mem_L/count_zero_reg[4]/QN} .original_name {Data_mem_L/count_zero[4]/q}
set_db {pin:MSDAP/Data_mem_L/count_zero_reg[3]/QN} .original_name {Data_mem_L/count_zero[3]/q}
set_db {pin:MSDAP/Data_mem_L/count_zero_reg[6]/QN} .original_name {Data_mem_L/count_zero[6]/q}
set_db {pin:MSDAP/Data_mem_L/count_zero_reg[7]/QN} .original_name {Data_mem_L/count_zero[7]/q}
set_db {pin:MSDAP/Data_mem_L/count_zero_reg[5]/QN} .original_name {Data_mem_L/count_zero[5]/q}
set_db pin:MSDAP/Data_mem_L/allzeros_reg/QN .original_name {Data_mem_L/allzeros/q}
set_db {pin:MSDAP/Data_mem_L/count_zero_reg[9]/QN} .original_name {Data_mem_L/count_zero[9]/q}
set_db {pin:MSDAP/Data_mem_R/count_zero_reg[1]/QN} .original_name {Data_mem_R/count_zero[1]/q}
set_db {pin:MSDAP/Data_mem_R/count_zero_reg[8]/QN} .original_name {Data_mem_R/count_zero[8]/q}
set_db {pin:MSDAP/Data_mem_R/count_zero_reg[2]/QN} .original_name {Data_mem_R/count_zero[2]/q}
set_db {pin:MSDAP/Data_mem_R/count_zero_reg[0]/QN} .original_name {Data_mem_R/count_zero[0]/q}
set_db {pin:MSDAP/Data_mem_R/count_zero_reg[4]/QN} .original_name {Data_mem_R/count_zero[4]/q}
set_db {pin:MSDAP/Data_mem_R/count_zero_reg[3]/QN} .original_name {Data_mem_R/count_zero[3]/q}
set_db {pin:MSDAP/Data_mem_R/count_zero_reg[6]/QN} .original_name {Data_mem_R/count_zero[6]/q}
set_db {pin:MSDAP/Data_mem_R/count_zero_reg[7]/QN} .original_name {Data_mem_R/count_zero[7]/q}
set_db {pin:MSDAP/Data_mem_R/count_zero_reg[5]/QN} .original_name {Data_mem_R/count_zero[5]/q}
set_db pin:MSDAP/Data_mem_R/allzeros_reg/QN .original_name {Data_mem_R/allzeros/q}
set_db {pin:MSDAP/Data_mem_R/count_zero_reg[9]/QN} .original_name {Data_mem_R/count_zero[9]/q}
set_db pin:MSDAP/PISOL/OutReady_reg/QN .original_name {PISOL/OutReady/q}
set_db pin:MSDAP/PISOL/OutputSerial_reg/QN .original_name {PISOL/OutputSerial/q}
set_db {pin:MSDAP/PISOL/count_bit_reg[0]/QN} .original_name {PISOL/count_bit[0]/q}
set_db {pin:MSDAP/PISOL/count_bit_reg[1]/QN} .original_name {PISOL/count_bit[1]/q}
set_db {pin:MSDAP/PISOL/count_bit_reg[2]/QN} .original_name {PISOL/count_bit[2]/q}
set_db {pin:MSDAP/PISOL/count_bit_reg[3]/QN} .original_name {PISOL/count_bit[3]/q}
set_db {pin:MSDAP/PISOL/count_bit_reg[4]/QN} .original_name {PISOL/count_bit[4]/q}
set_db {pin:MSDAP/PISOL/count_bit_reg[5]/QN} .original_name {PISOL/count_bit[5]/q}
set_db pin:MSDAP/PISOL/ready_out_reg/QN .original_name {PISOL/ready_out/q}
set_db {pin:MSDAP/PISOL/register_dataout_reg[0]/QN} .original_name {PISOL/register_dataout[0]/q}
set_db {pin:MSDAP/PISOL/register_dataout_reg[1]/QN} .original_name {PISOL/register_dataout[1]/q}
set_db {pin:MSDAP/PISOL/register_dataout_reg[2]/QN} .original_name {PISOL/register_dataout[2]/q}
set_db {pin:MSDAP/PISOL/register_dataout_reg[3]/QN} .original_name {PISOL/register_dataout[3]/q}
set_db {pin:MSDAP/PISOL/register_dataout_reg[4]/QN} .original_name {PISOL/register_dataout[4]/q}
set_db {pin:MSDAP/PISOL/register_dataout_reg[5]/QN} .original_name {PISOL/register_dataout[5]/q}
set_db {pin:MSDAP/PISOL/register_dataout_reg[6]/QN} .original_name {PISOL/register_dataout[6]/q}
set_db {pin:MSDAP/PISOL/register_dataout_reg[7]/QN} .original_name {PISOL/register_dataout[7]/q}
set_db {pin:MSDAP/PISOL/register_dataout_reg[8]/QN} .original_name {PISOL/register_dataout[8]/q}
set_db {pin:MSDAP/PISOL/register_dataout_reg[9]/QN} .original_name {PISOL/register_dataout[9]/q}
set_db {pin:MSDAP/PISOL/register_dataout_reg[10]/QN} .original_name {PISOL/register_dataout[10]/q}
set_db {pin:MSDAP/PISOL/register_dataout_reg[11]/QN} .original_name {PISOL/register_dataout[11]/q}
set_db {pin:MSDAP/PISOL/register_dataout_reg[12]/QN} .original_name {PISOL/register_dataout[12]/q}
set_db {pin:MSDAP/PISOL/register_dataout_reg[13]/QN} .original_name {PISOL/register_dataout[13]/q}
set_db {pin:MSDAP/PISOL/register_dataout_reg[14]/QN} .original_name {PISOL/register_dataout[14]/q}
set_db {pin:MSDAP/PISOL/register_dataout_reg[15]/QN} .original_name {PISOL/register_dataout[15]/q}
set_db {pin:MSDAP/PISOL/register_dataout_reg[16]/QN} .original_name {PISOL/register_dataout[16]/q}
set_db {pin:MSDAP/PISOL/register_dataout_reg[17]/QN} .original_name {PISOL/register_dataout[17]/q}
set_db {pin:MSDAP/PISOL/register_dataout_reg[18]/QN} .original_name {PISOL/register_dataout[18]/q}
set_db {pin:MSDAP/PISOL/register_dataout_reg[19]/QN} .original_name {PISOL/register_dataout[19]/q}
set_db {pin:MSDAP/PISOL/register_dataout_reg[20]/QN} .original_name {PISOL/register_dataout[20]/q}
set_db {pin:MSDAP/PISOL/register_dataout_reg[21]/QN} .original_name {PISOL/register_dataout[21]/q}
set_db {pin:MSDAP/PISOL/register_dataout_reg[22]/QN} .original_name {PISOL/register_dataout[22]/q}
set_db {pin:MSDAP/PISOL/register_dataout_reg[23]/QN} .original_name {PISOL/register_dataout[23]/q}
set_db {pin:MSDAP/PISOL/register_dataout_reg[24]/QN} .original_name {PISOL/register_dataout[24]/q}
set_db {pin:MSDAP/PISOL/register_dataout_reg[25]/QN} .original_name {PISOL/register_dataout[25]/q}
set_db {pin:MSDAP/PISOL/register_dataout_reg[26]/QN} .original_name {PISOL/register_dataout[26]/q}
set_db {pin:MSDAP/PISOL/register_dataout_reg[27]/QN} .original_name {PISOL/register_dataout[27]/q}
set_db {pin:MSDAP/PISOL/register_dataout_reg[28]/QN} .original_name {PISOL/register_dataout[28]/q}
set_db {pin:MSDAP/PISOL/register_dataout_reg[29]/QN} .original_name {PISOL/register_dataout[29]/q}
set_db {pin:MSDAP/PISOL/register_dataout_reg[30]/QN} .original_name {PISOL/register_dataout[30]/q}
set_db {pin:MSDAP/PISOL/register_dataout_reg[31]/QN} .original_name {PISOL/register_dataout[31]/q}
set_db {pin:MSDAP/PISOL/register_dataout_reg[32]/QN} .original_name {PISOL/register_dataout[32]/q}
set_db {pin:MSDAP/PISOL/register_dataout_reg[33]/QN} .original_name {PISOL/register_dataout[33]/q}
set_db {pin:MSDAP/PISOL/register_dataout_reg[34]/QN} .original_name {PISOL/register_dataout[34]/q}
set_db {pin:MSDAP/PISOL/register_dataout_reg[35]/QN} .original_name {PISOL/register_dataout[35]/q}
set_db {pin:MSDAP/PISOL/register_dataout_reg[36]/QN} .original_name {PISOL/register_dataout[36]/q}
set_db {pin:MSDAP/PISOL/register_dataout_reg[37]/QN} .original_name {PISOL/register_dataout[37]/q}
set_db {pin:MSDAP/PISOL/register_dataout_reg[38]/QN} .original_name {PISOL/register_dataout[38]/q}
set_db {pin:MSDAP/PISOL/register_dataout_reg[39]/QN} .original_name {PISOL/register_dataout[39]/q}
set_db pin:MSDAP/PISOR/OutReady_reg/QN .original_name {PISOR/OutReady/q}
set_db pin:MSDAP/PISOR/OutputSerial_reg/QN .original_name {PISOR/OutputSerial/q}
set_db {pin:MSDAP/PISOR/count_bit_reg[0]/QN} .original_name {PISOR/count_bit[0]/q}
set_db {pin:MSDAP/PISOR/count_bit_reg[1]/QN} .original_name {PISOR/count_bit[1]/q}
set_db {pin:MSDAP/PISOR/count_bit_reg[2]/QN} .original_name {PISOR/count_bit[2]/q}
set_db {pin:MSDAP/PISOR/count_bit_reg[3]/QN} .original_name {PISOR/count_bit[3]/q}
set_db {pin:MSDAP/PISOR/count_bit_reg[4]/QN} .original_name {PISOR/count_bit[4]/q}
set_db {pin:MSDAP/PISOR/count_bit_reg[5]/QN} .original_name {PISOR/count_bit[5]/q}
set_db pin:MSDAP/PISOR/ready_out_reg/QN .original_name {PISOR/ready_out/q}
set_db {pin:MSDAP/PISOR/register_dataout_reg[0]/QN} .original_name {PISOR/register_dataout[0]/q}
set_db {pin:MSDAP/PISOR/register_dataout_reg[1]/QN} .original_name {PISOR/register_dataout[1]/q}
set_db {pin:MSDAP/PISOR/register_dataout_reg[2]/QN} .original_name {PISOR/register_dataout[2]/q}
set_db {pin:MSDAP/PISOR/register_dataout_reg[3]/QN} .original_name {PISOR/register_dataout[3]/q}
set_db {pin:MSDAP/PISOR/register_dataout_reg[4]/QN} .original_name {PISOR/register_dataout[4]/q}
set_db {pin:MSDAP/PISOR/register_dataout_reg[5]/QN} .original_name {PISOR/register_dataout[5]/q}
set_db {pin:MSDAP/PISOR/register_dataout_reg[6]/QN} .original_name {PISOR/register_dataout[6]/q}
set_db {pin:MSDAP/PISOR/register_dataout_reg[7]/QN} .original_name {PISOR/register_dataout[7]/q}
set_db {pin:MSDAP/PISOR/register_dataout_reg[8]/QN} .original_name {PISOR/register_dataout[8]/q}
set_db {pin:MSDAP/PISOR/register_dataout_reg[9]/QN} .original_name {PISOR/register_dataout[9]/q}
set_db {pin:MSDAP/PISOR/register_dataout_reg[10]/QN} .original_name {PISOR/register_dataout[10]/q}
set_db {pin:MSDAP/PISOR/register_dataout_reg[11]/QN} .original_name {PISOR/register_dataout[11]/q}
set_db {pin:MSDAP/PISOR/register_dataout_reg[12]/QN} .original_name {PISOR/register_dataout[12]/q}
set_db {pin:MSDAP/PISOR/register_dataout_reg[13]/QN} .original_name {PISOR/register_dataout[13]/q}
set_db {pin:MSDAP/PISOR/register_dataout_reg[14]/QN} .original_name {PISOR/register_dataout[14]/q}
set_db {pin:MSDAP/PISOR/register_dataout_reg[15]/QN} .original_name {PISOR/register_dataout[15]/q}
set_db {pin:MSDAP/PISOR/register_dataout_reg[16]/QN} .original_name {PISOR/register_dataout[16]/q}
set_db {pin:MSDAP/PISOR/register_dataout_reg[17]/QN} .original_name {PISOR/register_dataout[17]/q}
set_db {pin:MSDAP/PISOR/register_dataout_reg[18]/QN} .original_name {PISOR/register_dataout[18]/q}
set_db {pin:MSDAP/PISOR/register_dataout_reg[19]/QN} .original_name {PISOR/register_dataout[19]/q}
set_db {pin:MSDAP/PISOR/register_dataout_reg[20]/QN} .original_name {PISOR/register_dataout[20]/q}
set_db {pin:MSDAP/PISOR/register_dataout_reg[21]/QN} .original_name {PISOR/register_dataout[21]/q}
set_db {pin:MSDAP/PISOR/register_dataout_reg[22]/QN} .original_name {PISOR/register_dataout[22]/q}
set_db {pin:MSDAP/PISOR/register_dataout_reg[23]/QN} .original_name {PISOR/register_dataout[23]/q}
set_db {pin:MSDAP/PISOR/register_dataout_reg[24]/QN} .original_name {PISOR/register_dataout[24]/q}
set_db {pin:MSDAP/PISOR/register_dataout_reg[25]/QN} .original_name {PISOR/register_dataout[25]/q}
set_db {pin:MSDAP/PISOR/register_dataout_reg[26]/QN} .original_name {PISOR/register_dataout[26]/q}
set_db {pin:MSDAP/PISOR/register_dataout_reg[27]/QN} .original_name {PISOR/register_dataout[27]/q}
set_db {pin:MSDAP/PISOR/register_dataout_reg[28]/QN} .original_name {PISOR/register_dataout[28]/q}
set_db {pin:MSDAP/PISOR/register_dataout_reg[29]/QN} .original_name {PISOR/register_dataout[29]/q}
set_db {pin:MSDAP/PISOR/register_dataout_reg[30]/QN} .original_name {PISOR/register_dataout[30]/q}
set_db {pin:MSDAP/PISOR/register_dataout_reg[31]/QN} .original_name {PISOR/register_dataout[31]/q}
set_db {pin:MSDAP/PISOR/register_dataout_reg[32]/QN} .original_name {PISOR/register_dataout[32]/q}
set_db {pin:MSDAP/PISOR/register_dataout_reg[33]/QN} .original_name {PISOR/register_dataout[33]/q}
set_db {pin:MSDAP/PISOR/register_dataout_reg[34]/QN} .original_name {PISOR/register_dataout[34]/q}
set_db {pin:MSDAP/PISOR/register_dataout_reg[35]/QN} .original_name {PISOR/register_dataout[35]/q}
set_db {pin:MSDAP/PISOR/register_dataout_reg[36]/QN} .original_name {PISOR/register_dataout[36]/q}
set_db {pin:MSDAP/PISOR/register_dataout_reg[37]/QN} .original_name {PISOR/register_dataout[37]/q}
set_db {pin:MSDAP/PISOR/register_dataout_reg[38]/QN} .original_name {PISOR/register_dataout[38]/q}
set_db {pin:MSDAP/PISOR/register_dataout_reg[39]/QN} .original_name {PISOR/register_dataout[39]/q}
set_db pin:MSDAP/alu_ctrl/clearL_reg/QN .original_name {alu_ctrl/clearL/q}
set_db pin:MSDAP/alu_ctrl/clearR_reg/QN .original_name {alu_ctrl/clearR/q}
set_db pin:MSDAP/alu_ctrl/enable_PISO_L_reg/QN .original_name {alu_ctrl/enable_PISO_L/q}
set_db pin:MSDAP/alu_ctrl/enable_PISO_R_reg/QN .original_name {alu_ctrl/enable_PISO_R/q}
set_db pin:MSDAP/alu_ctrl/inputL_enable_reg/QN .original_name {alu_ctrl/inputL_enable/q}
set_db pin:MSDAP/alu_ctrl/inputR_enable_reg/QN .original_name {alu_ctrl/inputR_enable/q}
set_db pin:MSDAP/alu_ctrl/loadL_reg/QN .original_name {alu_ctrl/loadL/q}
set_db pin:MSDAP/alu_ctrl/loadR_reg/QN .original_name {alu_ctrl/loadR/q}
set_db pin:MSDAP/alu_ctrl/shiftL_en_reg/QN .original_name {alu_ctrl/shiftL_en/q}
set_db pin:MSDAP/alu_ctrl/shiftR_en_reg/QN .original_name {alu_ctrl/shiftR_en/q}
set_db pin:MSDAP/alu_ctrl/addsubL_reg/QN .original_name {alu_ctrl/addsubL/q}
set_db pin:MSDAP/alu_ctrl/addsubR_reg/QN .original_name {alu_ctrl/addsubR/q}
set_db {pin:MSDAP/alu_ctrl/coeffL_addr_reg[0]/QN} .original_name {alu_ctrl/coeffL_addr[0]/q}
set_db {pin:MSDAP/alu_ctrl/coeffL_addr_reg[1]/QN} .original_name {alu_ctrl/coeffL_addr[1]/q}
set_db {pin:MSDAP/alu_ctrl/coeffL_addr_reg[2]/QN} .original_name {alu_ctrl/coeffL_addr[2]/q}
set_db {pin:MSDAP/alu_ctrl/coeffL_addr_reg[3]/QN} .original_name {alu_ctrl/coeffL_addr[3]/q}
set_db {pin:MSDAP/alu_ctrl/coeffL_addr_reg[4]/QN} .original_name {alu_ctrl/coeffL_addr[4]/q}
set_db {pin:MSDAP/alu_ctrl/coeffL_addr_reg[5]/QN} .original_name {alu_ctrl/coeffL_addr[5]/q}
set_db {pin:MSDAP/alu_ctrl/coeffL_addr_reg[6]/QN} .original_name {alu_ctrl/coeffL_addr[6]/q}
set_db {pin:MSDAP/alu_ctrl/coeffL_addr_reg[7]/QN} .original_name {alu_ctrl/coeffL_addr[7]/q}
set_db {pin:MSDAP/alu_ctrl/coeffL_addr_reg[8]/QN} .original_name {alu_ctrl/coeffL_addr[8]/q}
set_db pin:MSDAP/alu_ctrl/coeffL_enable_reg/QN .original_name {alu_ctrl/coeffL_enable/q}
set_db {pin:MSDAP/alu_ctrl/coeffR_addr_reg[0]/QN} .original_name {alu_ctrl/coeffR_addr[0]/q}
set_db {pin:MSDAP/alu_ctrl/coeffR_addr_reg[1]/QN} .original_name {alu_ctrl/coeffR_addr[1]/q}
set_db {pin:MSDAP/alu_ctrl/coeffR_addr_reg[2]/QN} .original_name {alu_ctrl/coeffR_addr[2]/q}
set_db {pin:MSDAP/alu_ctrl/coeffR_addr_reg[3]/QN} .original_name {alu_ctrl/coeffR_addr[3]/q}
set_db {pin:MSDAP/alu_ctrl/coeffR_addr_reg[4]/QN} .original_name {alu_ctrl/coeffR_addr[4]/q}
set_db {pin:MSDAP/alu_ctrl/coeffR_addr_reg[5]/QN} .original_name {alu_ctrl/coeffR_addr[5]/q}
set_db {pin:MSDAP/alu_ctrl/coeffR_addr_reg[6]/QN} .original_name {alu_ctrl/coeffR_addr[6]/q}
set_db {pin:MSDAP/alu_ctrl/coeffR_addr_reg[7]/QN} .original_name {alu_ctrl/coeffR_addr[7]/q}
set_db {pin:MSDAP/alu_ctrl/coeffR_addr_reg[8]/QN} .original_name {alu_ctrl/coeffR_addr[8]/q}
set_db pin:MSDAP/alu_ctrl/coeffR_enable_reg/QN .original_name {alu_ctrl/coeffR_enable/q}
set_db {pin:MSDAP/alu_ctrl/inputL_addr_reg[0]/QN} .original_name {alu_ctrl/inputL_addr[0]/q}
set_db {pin:MSDAP/alu_ctrl/inputL_addr_reg[1]/QN} .original_name {alu_ctrl/inputL_addr[1]/q}
set_db {pin:MSDAP/alu_ctrl/inputL_addr_reg[2]/QN} .original_name {alu_ctrl/inputL_addr[2]/q}
set_db {pin:MSDAP/alu_ctrl/inputL_addr_reg[3]/QN} .original_name {alu_ctrl/inputL_addr[3]/q}
set_db {pin:MSDAP/alu_ctrl/inputL_addr_reg[4]/QN} .original_name {alu_ctrl/inputL_addr[4]/q}
set_db {pin:MSDAP/alu_ctrl/inputL_addr_reg[5]/QN} .original_name {alu_ctrl/inputL_addr[5]/q}
set_db {pin:MSDAP/alu_ctrl/inputL_addr_reg[6]/QN} .original_name {alu_ctrl/inputL_addr[6]/q}
set_db {pin:MSDAP/alu_ctrl/inputL_addr_reg[7]/QN} .original_name {alu_ctrl/inputL_addr[7]/q}
set_db {pin:MSDAP/alu_ctrl/inputR_addr_reg[0]/QN} .original_name {alu_ctrl/inputR_addr[0]/q}
set_db {pin:MSDAP/alu_ctrl/inputR_addr_reg[1]/QN} .original_name {alu_ctrl/inputR_addr[1]/q}
set_db {pin:MSDAP/alu_ctrl/inputR_addr_reg[2]/QN} .original_name {alu_ctrl/inputR_addr[2]/q}
set_db {pin:MSDAP/alu_ctrl/inputR_addr_reg[3]/QN} .original_name {alu_ctrl/inputR_addr[3]/q}
set_db {pin:MSDAP/alu_ctrl/inputR_addr_reg[4]/QN} .original_name {alu_ctrl/inputR_addr[4]/q}
set_db {pin:MSDAP/alu_ctrl/inputR_addr_reg[5]/QN} .original_name {alu_ctrl/inputR_addr[5]/q}
set_db {pin:MSDAP/alu_ctrl/inputR_addr_reg[6]/QN} .original_name {alu_ctrl/inputR_addr[6]/q}
set_db {pin:MSDAP/alu_ctrl/inputR_addr_reg[7]/QN} .original_name {alu_ctrl/inputR_addr[7]/q}
set_db {pin:MSDAP/alu_ctrl/kL_reg[0]/QN} .original_name {alu_ctrl/kL[0]/q}
set_db {pin:MSDAP/alu_ctrl/kL_reg[1]/QN} .original_name {alu_ctrl/kL[1]/q}
set_db {pin:MSDAP/alu_ctrl/kL_reg[2]/QN} .original_name {alu_ctrl/kL[2]/q}
set_db {pin:MSDAP/alu_ctrl/kL_reg[3]/QN} .original_name {alu_ctrl/kL[3]/q}
set_db {pin:MSDAP/alu_ctrl/kL_reg[4]/QN} .original_name {alu_ctrl/kL[4]/q}
set_db {pin:MSDAP/alu_ctrl/kL_reg[5]/QN} .original_name {alu_ctrl/kL[5]/q}
set_db {pin:MSDAP/alu_ctrl/kL_reg[6]/QN} .original_name {alu_ctrl/kL[6]/q}
set_db {pin:MSDAP/alu_ctrl/kL_reg[7]/QN} .original_name {alu_ctrl/kL[7]/q}
set_db {pin:MSDAP/alu_ctrl/kR_reg[0]/QN} .original_name {alu_ctrl/kR[0]/q}
set_db {pin:MSDAP/alu_ctrl/kR_reg[1]/QN} .original_name {alu_ctrl/kR[1]/q}
set_db {pin:MSDAP/alu_ctrl/kR_reg[2]/QN} .original_name {alu_ctrl/kR[2]/q}
set_db {pin:MSDAP/alu_ctrl/kR_reg[3]/QN} .original_name {alu_ctrl/kR[3]/q}
set_db {pin:MSDAP/alu_ctrl/kR_reg[4]/QN} .original_name {alu_ctrl/kR[4]/q}
set_db {pin:MSDAP/alu_ctrl/kR_reg[5]/QN} .original_name {alu_ctrl/kR[5]/q}
set_db {pin:MSDAP/alu_ctrl/kR_reg[6]/QN} .original_name {alu_ctrl/kR[6]/q}
set_db {pin:MSDAP/alu_ctrl/kR_reg[7]/QN} .original_name {alu_ctrl/kR[7]/q}
set_db pin:MSDAP/alu_ctrl/memL_overflow_reg/QN .original_name {alu_ctrl/memL_overflow/q}
set_db pin:MSDAP/alu_ctrl/memR_overflow_reg/QN .original_name {alu_ctrl/memR_overflow/q}
set_db {pin:MSDAP/alu_ctrl/next_stateL_reg[0]/QN} .original_name {alu_ctrl/next_stateL[0]/q}
set_db {pin:MSDAP/alu_ctrl/next_stateL_reg[1]/QN} .original_name {alu_ctrl/next_stateL[1]/q}
set_db {pin:MSDAP/alu_ctrl/next_stateR_reg[0]/QN} .original_name {alu_ctrl/next_stateR[0]/q}
set_db pin:MSDAP/alu_ctrl/outL_reg/QN .original_name {alu_ctrl/outL/q}
set_db pin:MSDAP/alu_ctrl/outR_reg/QN .original_name {alu_ctrl/outR/q}
set_db {pin:MSDAP/alu_ctrl/rjL_addr_reg[0]/QN} .original_name {alu_ctrl/rjL_addr[0]/q}
set_db {pin:MSDAP/alu_ctrl/rjL_addr_reg[1]/QN} .original_name {alu_ctrl/rjL_addr[1]/q}
set_db {pin:MSDAP/alu_ctrl/rjL_addr_reg[2]/QN} .original_name {alu_ctrl/rjL_addr[2]/q}
set_db {pin:MSDAP/alu_ctrl/rjL_addr_reg[3]/QN} .original_name {alu_ctrl/rjL_addr[3]/q}
set_db {pin:MSDAP/alu_ctrl/rjR_addr_reg[0]/QN} .original_name {alu_ctrl/rjR_addr[0]/q}
set_db {pin:MSDAP/alu_ctrl/rjR_addr_reg[1]/QN} .original_name {alu_ctrl/rjR_addr[1]/q}
set_db {pin:MSDAP/alu_ctrl/rjR_addr_reg[2]/QN} .original_name {alu_ctrl/rjR_addr[2]/q}
set_db {pin:MSDAP/alu_ctrl/rjR_addr_reg[3]/QN} .original_name {alu_ctrl/rjR_addr[3]/q}
set_db pin:MSDAP/alu_ctrl/start_workL_reg/QN .original_name {alu_ctrl/start_workL/q}
set_db pin:MSDAP/alu_ctrl/start_workR_reg/QN .original_name {alu_ctrl/start_workR/q}
set_db pin:MSDAP/alu_ctrl/work_statusL_reg/QN .original_name {alu_ctrl/work_statusL/q}
set_db pin:MSDAP/alu_ctrl/work_statusR_reg/QN .original_name {alu_ctrl/work_statusR/q}
set_db {pin:MSDAP/alu_ctrl/xcntL_reg[0]/QN} .original_name {alu_ctrl/xcntL[0]/q}
set_db {pin:MSDAP/alu_ctrl/xcntL_reg[1]/QN} .original_name {alu_ctrl/xcntL[1]/q}
set_db {pin:MSDAP/alu_ctrl/xcntL_reg[2]/QN} .original_name {alu_ctrl/xcntL[2]/q}
set_db {pin:MSDAP/alu_ctrl/xcntL_reg[3]/QN} .original_name {alu_ctrl/xcntL[3]/q}
set_db {pin:MSDAP/alu_ctrl/xcntL_reg[4]/QN} .original_name {alu_ctrl/xcntL[4]/q}
set_db {pin:MSDAP/alu_ctrl/xcntL_reg[5]/QN} .original_name {alu_ctrl/xcntL[5]/q}
set_db {pin:MSDAP/alu_ctrl/xcntL_reg[6]/QN} .original_name {alu_ctrl/xcntL[6]/q}
set_db {pin:MSDAP/alu_ctrl/xcntL_reg[7]/QN} .original_name {alu_ctrl/xcntL[7]/q}
set_db {pin:MSDAP/alu_ctrl/xcntR_reg[0]/QN} .original_name {alu_ctrl/xcntR[0]/q}
set_db {pin:MSDAP/alu_ctrl/xcntR_reg[1]/QN} .original_name {alu_ctrl/xcntR[1]/q}
set_db {pin:MSDAP/alu_ctrl/xcntR_reg[2]/QN} .original_name {alu_ctrl/xcntR[2]/q}
set_db {pin:MSDAP/alu_ctrl/xcntR_reg[3]/QN} .original_name {alu_ctrl/xcntR[3]/q}
set_db {pin:MSDAP/alu_ctrl/xcntR_reg[4]/QN} .original_name {alu_ctrl/xcntR[4]/q}
set_db {pin:MSDAP/alu_ctrl/xcntR_reg[5]/QN} .original_name {alu_ctrl/xcntR[5]/q}
set_db {pin:MSDAP/alu_ctrl/xcntR_reg[6]/QN} .original_name {alu_ctrl/xcntR[6]/q}
set_db {pin:MSDAP/alu_ctrl/xcntR_reg[7]/QN} .original_name {alu_ctrl/xcntR[7]/q}
set_db pin:MSDAP/main_ctrl/Clear_reg/QN .original_name {main_ctrl/Clear/q}
set_db {pin:MSDAP/main_ctrl/Coefficient_Read_Address_reg[0]/QN} .original_name {main_ctrl/Coefficient_Read_Address[0]/q}
set_db {pin:MSDAP/main_ctrl/Coefficient_Read_Address_reg[1]/QN} .original_name {main_ctrl/Coefficient_Read_Address[1]/q}
set_db {pin:MSDAP/main_ctrl/Coefficient_Read_Address_reg[2]/QN} .original_name {main_ctrl/Coefficient_Read_Address[2]/q}
set_db {pin:MSDAP/main_ctrl/Coefficient_Read_Address_reg[3]/QN} .original_name {main_ctrl/Coefficient_Read_Address[3]/q}
set_db {pin:MSDAP/main_ctrl/Coefficient_Read_Address_reg[4]/QN} .original_name {main_ctrl/Coefficient_Read_Address[4]/q}
set_db {pin:MSDAP/main_ctrl/Coefficient_Read_Address_reg[5]/QN} .original_name {main_ctrl/Coefficient_Read_Address[5]/q}
set_db {pin:MSDAP/main_ctrl/Coefficient_Read_Address_reg[6]/QN} .original_name {main_ctrl/Coefficient_Read_Address[6]/q}
set_db {pin:MSDAP/main_ctrl/Coefficient_Read_Address_reg[7]/QN} .original_name {main_ctrl/Coefficient_Read_Address[7]/q}
set_db {pin:MSDAP/main_ctrl/Coefficient_Read_Address_reg[8]/QN} .original_name {main_ctrl/Coefficient_Read_Address[8]/q}
set_db pin:MSDAP/main_ctrl/Coefficient_Read_Enable_reg/QN .original_name {main_ctrl/Coefficient_Read_Enable/q}
set_db pin:MSDAP/main_ctrl/Data_Read_Enable_reg/QN .original_name {main_ctrl/Data_Read_Enable/q}
set_db pin:MSDAP/main_ctrl/InReady_reg/QN .original_name {main_ctrl/InReady/q}
set_db {pin:MSDAP/main_ctrl/Input_Read_Address_reg[0]/QN} .original_name {main_ctrl/Input_Read_Address[0]/q}
set_db {pin:MSDAP/main_ctrl/Input_Read_Address_reg[1]/QN} .original_name {main_ctrl/Input_Read_Address[1]/q}
set_db {pin:MSDAP/main_ctrl/Input_Read_Address_reg[2]/QN} .original_name {main_ctrl/Input_Read_Address[2]/q}
set_db {pin:MSDAP/main_ctrl/Input_Read_Address_reg[3]/QN} .original_name {main_ctrl/Input_Read_Address[3]/q}
set_db {pin:MSDAP/main_ctrl/Input_Read_Address_reg[4]/QN} .original_name {main_ctrl/Input_Read_Address[4]/q}
set_db {pin:MSDAP/main_ctrl/Input_Read_Address_reg[5]/QN} .original_name {main_ctrl/Input_Read_Address[5]/q}
set_db {pin:MSDAP/main_ctrl/Input_Read_Address_reg[6]/QN} .original_name {main_ctrl/Input_Read_Address[6]/q}
set_db {pin:MSDAP/main_ctrl/Input_Read_Address_reg[7]/QN} .original_name {main_ctrl/Input_Read_Address[7]/q}
set_db {pin:MSDAP/main_ctrl/Rj_Read_Address_reg[0]/QN} .original_name {main_ctrl/Rj_Read_Address[0]/q}
set_db {pin:MSDAP/main_ctrl/Rj_Read_Address_reg[1]/QN} .original_name {main_ctrl/Rj_Read_Address[1]/q}
set_db {pin:MSDAP/main_ctrl/Rj_Read_Address_reg[2]/QN} .original_name {main_ctrl/Rj_Read_Address[2]/q}
set_db {pin:MSDAP/main_ctrl/Rj_Read_Address_reg[3]/QN} .original_name {main_ctrl/Rj_Read_Address[3]/q}
set_db pin:MSDAP/main_ctrl/Rj_Read_Enable_reg/QN .original_name {main_ctrl/Rj_Read_Enable/q}
set_db {pin:MSDAP/main_ctrl/count_coeff_reg[0]/QN} .original_name {main_ctrl/count_coeff[0]/q}
set_db {pin:MSDAP/main_ctrl/count_coeff_reg[1]/QN} .original_name {main_ctrl/count_coeff[1]/q}
set_db {pin:MSDAP/main_ctrl/count_coeff_reg[2]/QN} .original_name {main_ctrl/count_coeff[2]/q}
set_db {pin:MSDAP/main_ctrl/count_coeff_reg[3]/QN} .original_name {main_ctrl/count_coeff[3]/q}
set_db {pin:MSDAP/main_ctrl/count_coeff_reg[4]/QN} .original_name {main_ctrl/count_coeff[4]/q}
set_db {pin:MSDAP/main_ctrl/count_coeff_reg[5]/QN} .original_name {main_ctrl/count_coeff[5]/q}
set_db {pin:MSDAP/main_ctrl/count_coeff_reg[6]/QN} .original_name {main_ctrl/count_coeff[6]/q}
set_db {pin:MSDAP/main_ctrl/count_coeff_reg[7]/QN} .original_name {main_ctrl/count_coeff[7]/q}
set_db {pin:MSDAP/main_ctrl/count_coeff_reg[8]/QN} .original_name {main_ctrl/count_coeff[8]/q}
set_db {pin:MSDAP/main_ctrl/count_coeff_reg[9]/QN} .original_name {main_ctrl/count_coeff[9]/q}
set_db {pin:MSDAP/main_ctrl/count_data_reg[0]/QN} .original_name {main_ctrl/count_data[0]/q}
set_db {pin:MSDAP/main_ctrl/count_data_reg[1]/QN} .original_name {main_ctrl/count_data[1]/q}
set_db {pin:MSDAP/main_ctrl/count_data_reg[2]/QN} .original_name {main_ctrl/count_data[2]/q}
set_db {pin:MSDAP/main_ctrl/count_data_reg[3]/QN} .original_name {main_ctrl/count_data[3]/q}
set_db {pin:MSDAP/main_ctrl/count_data_reg[4]/QN} .original_name {main_ctrl/count_data[4]/q}
set_db {pin:MSDAP/main_ctrl/count_data_reg[5]/QN} .original_name {main_ctrl/count_data[5]/q}
set_db {pin:MSDAP/main_ctrl/count_data_reg[6]/QN} .original_name {main_ctrl/count_data[6]/q}
set_db {pin:MSDAP/main_ctrl/count_data_reg[7]/QN} .original_name {main_ctrl/count_data[7]/q}
set_db {pin:MSDAP/main_ctrl/count_rj_reg[0]/QN} .original_name {main_ctrl/count_rj[0]/q}
set_db {pin:MSDAP/main_ctrl/count_rj_reg[1]/QN} .original_name {main_ctrl/count_rj[1]/q}
set_db {pin:MSDAP/main_ctrl/count_rj_reg[2]/QN} .original_name {main_ctrl/count_rj[2]/q}
set_db {pin:MSDAP/main_ctrl/count_rj_reg[3]/QN} .original_name {main_ctrl/count_rj[3]/q}
set_db {pin:MSDAP/main_ctrl/count_rj_reg[4]/QN} .original_name {main_ctrl/count_rj[4]/q}
set_db pin:MSDAP/main_ctrl/sleep_flag_reg/QN .original_name {main_ctrl/sleep_flag/q}
set_db {pin:MSDAP/main_ctrl/state_next_reg[0]/QN} .original_name {main_ctrl/state_next[0]/q}
set_db {pin:MSDAP/main_ctrl/state_next_reg[1]/QN} .original_name {main_ctrl/state_next[1]/q}
set_db {pin:MSDAP/main_ctrl/state_next_reg[2]/QN} .original_name {main_ctrl/state_next[2]/q}
set_db {pin:MSDAP/main_ctrl/state_next_reg[3]/QN} .original_name {main_ctrl/state_next[3]/q}
set_db {pin:MSDAP/main_ctrl/state_present_reg[0]/QN} .original_name {main_ctrl/state_present[0]/q}
set_db {pin:MSDAP/main_ctrl/state_present_reg[1]/QN} .original_name {main_ctrl/state_present[1]/q}
set_db {pin:MSDAP/main_ctrl/state_present_reg[2]/QN} .original_name {main_ctrl/state_present[2]/q}
set_db {pin:MSDAP/main_ctrl/state_present_reg[3]/QN} .original_name {main_ctrl/state_present[3]/q}
set_db pin:MSDAP/main_ctrl/tk_reg/QN .original_name {main_ctrl/tk/q}
set_db pin:MSDAP/pipo/input_ready_reg/QN .original_name {pipo/input_ready/q}
set_db {pin:MSDAP/pipo/bitpos_reg[0]/QN} .original_name {pipo/bitpos[0]/q}
set_db {pin:MSDAP/pipo/bitpos_reg[1]/QN} .original_name {pipo/bitpos[1]/q}
set_db {pin:MSDAP/pipo/bitpos_reg[2]/QN} .original_name {pipo/bitpos[2]/q}
set_db {pin:MSDAP/pipo/bitpos_reg[3]/QN} .original_name {pipo/bitpos[3]/q}
set_db pin:MSDAP/pipo/continueFrame_reg/QN .original_name {pipo/continueFrame/q}
set_db {pin:MSDAP/pipo/dataL_reg[0]/QN} .original_name {pipo/dataL[0]/q}
set_db {pin:MSDAP/pipo/dataL_reg[1]/QN} .original_name {pipo/dataL[1]/q}
set_db {pin:MSDAP/pipo/dataL_reg[2]/QN} .original_name {pipo/dataL[2]/q}
set_db {pin:MSDAP/pipo/dataL_reg[3]/QN} .original_name {pipo/dataL[3]/q}
set_db {pin:MSDAP/pipo/dataL_reg[4]/QN} .original_name {pipo/dataL[4]/q}
set_db {pin:MSDAP/pipo/dataL_reg[5]/QN} .original_name {pipo/dataL[5]/q}
set_db {pin:MSDAP/pipo/dataL_reg[6]/QN} .original_name {pipo/dataL[6]/q}
set_db {pin:MSDAP/pipo/dataL_reg[7]/QN} .original_name {pipo/dataL[7]/q}
set_db {pin:MSDAP/pipo/dataL_reg[8]/QN} .original_name {pipo/dataL[8]/q}
set_db {pin:MSDAP/pipo/dataL_reg[9]/QN} .original_name {pipo/dataL[9]/q}
set_db {pin:MSDAP/pipo/dataL_reg[10]/QN} .original_name {pipo/dataL[10]/q}
set_db {pin:MSDAP/pipo/dataL_reg[11]/QN} .original_name {pipo/dataL[11]/q}
set_db {pin:MSDAP/pipo/dataL_reg[12]/QN} .original_name {pipo/dataL[12]/q}
set_db {pin:MSDAP/pipo/dataL_reg[13]/QN} .original_name {pipo/dataL[13]/q}
set_db {pin:MSDAP/pipo/dataL_reg[14]/QN} .original_name {pipo/dataL[14]/q}
set_db {pin:MSDAP/pipo/dataL_reg[15]/QN} .original_name {pipo/dataL[15]/q}
set_db {pin:MSDAP/pipo/dataR_reg[0]/QN} .original_name {pipo/dataR[0]/q}
set_db {pin:MSDAP/pipo/dataR_reg[1]/QN} .original_name {pipo/dataR[1]/q}
set_db {pin:MSDAP/pipo/dataR_reg[2]/QN} .original_name {pipo/dataR[2]/q}
set_db {pin:MSDAP/pipo/dataR_reg[3]/QN} .original_name {pipo/dataR[3]/q}
set_db {pin:MSDAP/pipo/dataR_reg[4]/QN} .original_name {pipo/dataR[4]/q}
set_db {pin:MSDAP/pipo/dataR_reg[5]/QN} .original_name {pipo/dataR[5]/q}
set_db {pin:MSDAP/pipo/dataR_reg[6]/QN} .original_name {pipo/dataR[6]/q}
set_db {pin:MSDAP/pipo/dataR_reg[7]/QN} .original_name {pipo/dataR[7]/q}
set_db {pin:MSDAP/pipo/dataR_reg[8]/QN} .original_name {pipo/dataR[8]/q}
set_db {pin:MSDAP/pipo/dataR_reg[9]/QN} .original_name {pipo/dataR[9]/q}
set_db {pin:MSDAP/pipo/dataR_reg[10]/QN} .original_name {pipo/dataR[10]/q}
set_db {pin:MSDAP/pipo/dataR_reg[11]/QN} .original_name {pipo/dataR[11]/q}
set_db {pin:MSDAP/pipo/dataR_reg[12]/QN} .original_name {pipo/dataR[12]/q}
set_db {pin:MSDAP/pipo/dataR_reg[13]/QN} .original_name {pipo/dataR[13]/q}
set_db {pin:MSDAP/pipo/dataR_reg[14]/QN} .original_name {pipo/dataR[14]/q}
set_db {pin:MSDAP/pipo/dataR_reg[15]/QN} .original_name {pipo/dataR[15]/q}
set_db {pin:MSDAP/shiftL/tempreg_reg[0]/QN} .original_name {shiftL/tempreg[0]/q}
set_db {pin:MSDAP/shiftL/tempreg_reg[1]/QN} .original_name {shiftL/tempreg[1]/q}
set_db {pin:MSDAP/shiftL/tempreg_reg[2]/QN} .original_name {shiftL/tempreg[2]/q}
set_db {pin:MSDAP/shiftL/tempreg_reg[3]/QN} .original_name {shiftL/tempreg[3]/q}
set_db {pin:MSDAP/shiftL/tempreg_reg[4]/QN} .original_name {shiftL/tempreg[4]/q}
set_db {pin:MSDAP/shiftL/tempreg_reg[5]/QN} .original_name {shiftL/tempreg[5]/q}
set_db {pin:MSDAP/shiftL/tempreg_reg[6]/QN} .original_name {shiftL/tempreg[6]/q}
set_db {pin:MSDAP/shiftL/tempreg_reg[7]/QN} .original_name {shiftL/tempreg[7]/q}
set_db {pin:MSDAP/shiftL/tempreg_reg[8]/QN} .original_name {shiftL/tempreg[8]/q}
set_db {pin:MSDAP/shiftL/tempreg_reg[9]/QN} .original_name {shiftL/tempreg[9]/q}
set_db {pin:MSDAP/shiftL/tempreg_reg[10]/QN} .original_name {shiftL/tempreg[10]/q}
set_db {pin:MSDAP/shiftL/tempreg_reg[11]/QN} .original_name {shiftL/tempreg[11]/q}
set_db {pin:MSDAP/shiftL/tempreg_reg[12]/QN} .original_name {shiftL/tempreg[12]/q}
set_db {pin:MSDAP/shiftL/tempreg_reg[13]/QN} .original_name {shiftL/tempreg[13]/q}
set_db {pin:MSDAP/shiftL/tempreg_reg[14]/QN} .original_name {shiftL/tempreg[14]/q}
set_db {pin:MSDAP/shiftL/tempreg_reg[15]/QN} .original_name {shiftL/tempreg[15]/q}
set_db {pin:MSDAP/shiftL/tempreg_reg[16]/QN} .original_name {shiftL/tempreg[16]/q}
set_db {pin:MSDAP/shiftL/tempreg_reg[17]/QN} .original_name {shiftL/tempreg[17]/q}
set_db {pin:MSDAP/shiftL/tempreg_reg[18]/QN} .original_name {shiftL/tempreg[18]/q}
set_db {pin:MSDAP/shiftL/tempreg_reg[19]/QN} .original_name {shiftL/tempreg[19]/q}
set_db {pin:MSDAP/shiftL/tempreg_reg[20]/QN} .original_name {shiftL/tempreg[20]/q}
set_db {pin:MSDAP/shiftL/tempreg_reg[21]/QN} .original_name {shiftL/tempreg[21]/q}
set_db {pin:MSDAP/shiftL/tempreg_reg[22]/QN} .original_name {shiftL/tempreg[22]/q}
set_db {pin:MSDAP/shiftL/tempreg_reg[23]/QN} .original_name {shiftL/tempreg[23]/q}
set_db {pin:MSDAP/shiftL/tempreg_reg[24]/QN} .original_name {shiftL/tempreg[24]/q}
set_db {pin:MSDAP/shiftL/tempreg_reg[25]/QN} .original_name {shiftL/tempreg[25]/q}
set_db {pin:MSDAP/shiftL/tempreg_reg[26]/QN} .original_name {shiftL/tempreg[26]/q}
set_db {pin:MSDAP/shiftL/tempreg_reg[27]/QN} .original_name {shiftL/tempreg[27]/q}
set_db {pin:MSDAP/shiftL/tempreg_reg[28]/QN} .original_name {shiftL/tempreg[28]/q}
set_db {pin:MSDAP/shiftL/tempreg_reg[29]/QN} .original_name {shiftL/tempreg[29]/q}
set_db {pin:MSDAP/shiftL/tempreg_reg[30]/QN} .original_name {shiftL/tempreg[30]/q}
set_db {pin:MSDAP/shiftL/tempreg_reg[31]/QN} .original_name {shiftL/tempreg[31]/q}
set_db {pin:MSDAP/shiftL/tempreg_reg[32]/QN} .original_name {shiftL/tempreg[32]/q}
set_db {pin:MSDAP/shiftL/tempreg_reg[33]/QN} .original_name {shiftL/tempreg[33]/q}
set_db {pin:MSDAP/shiftL/tempreg_reg[34]/QN} .original_name {shiftL/tempreg[34]/q}
set_db {pin:MSDAP/shiftL/tempreg_reg[35]/QN} .original_name {shiftL/tempreg[35]/q}
set_db {pin:MSDAP/shiftL/tempreg_reg[36]/QN} .original_name {shiftL/tempreg[36]/q}
set_db {pin:MSDAP/shiftL/tempreg_reg[37]/QN} .original_name {shiftL/tempreg[37]/q}
set_db {pin:MSDAP/shiftL/tempreg_reg[38]/QN} .original_name {shiftL/tempreg[38]/q}
set_db {pin:MSDAP/shiftL/tempreg_reg[39]/QN} .original_name {shiftL/tempreg[39]/q}
set_db {pin:MSDAP/shiftR/tempreg_reg[0]/QN} .original_name {shiftR/tempreg[0]/q}
set_db {pin:MSDAP/shiftR/tempreg_reg[1]/QN} .original_name {shiftR/tempreg[1]/q}
set_db {pin:MSDAP/shiftR/tempreg_reg[2]/QN} .original_name {shiftR/tempreg[2]/q}
set_db {pin:MSDAP/shiftR/tempreg_reg[3]/QN} .original_name {shiftR/tempreg[3]/q}
set_db {pin:MSDAP/shiftR/tempreg_reg[4]/QN} .original_name {shiftR/tempreg[4]/q}
set_db {pin:MSDAP/shiftR/tempreg_reg[5]/QN} .original_name {shiftR/tempreg[5]/q}
set_db {pin:MSDAP/shiftR/tempreg_reg[6]/QN} .original_name {shiftR/tempreg[6]/q}
set_db {pin:MSDAP/shiftR/tempreg_reg[7]/QN} .original_name {shiftR/tempreg[7]/q}
set_db {pin:MSDAP/shiftR/tempreg_reg[8]/QN} .original_name {shiftR/tempreg[8]/q}
set_db {pin:MSDAP/shiftR/tempreg_reg[9]/QN} .original_name {shiftR/tempreg[9]/q}
set_db {pin:MSDAP/shiftR/tempreg_reg[10]/QN} .original_name {shiftR/tempreg[10]/q}
set_db {pin:MSDAP/shiftR/tempreg_reg[11]/QN} .original_name {shiftR/tempreg[11]/q}
set_db {pin:MSDAP/shiftR/tempreg_reg[12]/QN} .original_name {shiftR/tempreg[12]/q}
set_db {pin:MSDAP/shiftR/tempreg_reg[13]/QN} .original_name {shiftR/tempreg[13]/q}
set_db {pin:MSDAP/shiftR/tempreg_reg[14]/QN} .original_name {shiftR/tempreg[14]/q}
set_db {pin:MSDAP/shiftR/tempreg_reg[15]/QN} .original_name {shiftR/tempreg[15]/q}
set_db {pin:MSDAP/shiftR/tempreg_reg[16]/QN} .original_name {shiftR/tempreg[16]/q}
set_db {pin:MSDAP/shiftR/tempreg_reg[17]/QN} .original_name {shiftR/tempreg[17]/q}
set_db {pin:MSDAP/shiftR/tempreg_reg[18]/QN} .original_name {shiftR/tempreg[18]/q}
set_db {pin:MSDAP/shiftR/tempreg_reg[19]/QN} .original_name {shiftR/tempreg[19]/q}
set_db {pin:MSDAP/shiftR/tempreg_reg[20]/QN} .original_name {shiftR/tempreg[20]/q}
set_db {pin:MSDAP/shiftR/tempreg_reg[21]/QN} .original_name {shiftR/tempreg[21]/q}
set_db {pin:MSDAP/shiftR/tempreg_reg[22]/QN} .original_name {shiftR/tempreg[22]/q}
set_db {pin:MSDAP/shiftR/tempreg_reg[23]/QN} .original_name {shiftR/tempreg[23]/q}
set_db {pin:MSDAP/shiftR/tempreg_reg[24]/QN} .original_name {shiftR/tempreg[24]/q}
set_db {pin:MSDAP/shiftR/tempreg_reg[25]/QN} .original_name {shiftR/tempreg[25]/q}
set_db {pin:MSDAP/shiftR/tempreg_reg[26]/QN} .original_name {shiftR/tempreg[26]/q}
set_db {pin:MSDAP/shiftR/tempreg_reg[27]/QN} .original_name {shiftR/tempreg[27]/q}
set_db {pin:MSDAP/shiftR/tempreg_reg[28]/QN} .original_name {shiftR/tempreg[28]/q}
set_db {pin:MSDAP/shiftR/tempreg_reg[29]/QN} .original_name {shiftR/tempreg[29]/q}
set_db {pin:MSDAP/shiftR/tempreg_reg[30]/QN} .original_name {shiftR/tempreg[30]/q}
set_db {pin:MSDAP/shiftR/tempreg_reg[31]/QN} .original_name {shiftR/tempreg[31]/q}
set_db {pin:MSDAP/shiftR/tempreg_reg[32]/QN} .original_name {shiftR/tempreg[32]/q}
set_db {pin:MSDAP/shiftR/tempreg_reg[33]/QN} .original_name {shiftR/tempreg[33]/q}
set_db {pin:MSDAP/shiftR/tempreg_reg[34]/QN} .original_name {shiftR/tempreg[34]/q}
set_db {pin:MSDAP/shiftR/tempreg_reg[35]/QN} .original_name {shiftR/tempreg[35]/q}
set_db {pin:MSDAP/shiftR/tempreg_reg[36]/QN} .original_name {shiftR/tempreg[36]/q}
set_db {pin:MSDAP/shiftR/tempreg_reg[37]/QN} .original_name {shiftR/tempreg[37]/q}
set_db {pin:MSDAP/shiftR/tempreg_reg[38]/QN} .original_name {shiftR/tempreg[38]/q}
set_db {pin:MSDAP/shiftR/tempreg_reg[39]/QN} .original_name {shiftR/tempreg[39]/q}
