set_clock_latency -source -early -min -rise  -40.9021 [get_ports {Dclk}] -clock Dclk 
set_clock_latency -source -early -min -fall  -42.2632 [get_ports {Dclk}] -clock Dclk 
set_clock_latency -source -early -max -rise  -40.9021 [get_ports {Dclk}] -clock Dclk 
set_clock_latency -source -early -max -fall  -42.2632 [get_ports {Dclk}] -clock Dclk 
set_clock_latency -source -late -min -rise  -40.9021 [get_ports {Dclk}] -clock Dclk 
set_clock_latency -source -late -min -fall  -42.2632 [get_ports {Dclk}] -clock Dclk 
set_clock_latency -source -late -max -rise  -40.9021 [get_ports {Dclk}] -clock Dclk 
set_clock_latency -source -late -max -fall  -42.2632 [get_ports {Dclk}] -clock Dclk 
set_clock_latency -source -early -min -rise  -84.1677 [get_ports {Sclk}] -clock Sclk 
set_clock_latency -source -early -min -fall  -88.0231 [get_ports {Sclk}] -clock Sclk 
set_clock_latency -source -early -max -rise  -84.1677 [get_ports {Sclk}] -clock Sclk 
set_clock_latency -source -early -max -fall  -88.0231 [get_ports {Sclk}] -clock Sclk 
set_clock_latency -source -late -min -rise  -84.1677 [get_ports {Sclk}] -clock Sclk 
set_clock_latency -source -late -min -fall  -88.0231 [get_ports {Sclk}] -clock Sclk 
set_clock_latency -source -late -max -rise  -84.1677 [get_ports {Sclk}] -clock Sclk 
set_clock_latency -source -late -max -fall  -88.0231 [get_ports {Sclk}] -clock Sclk 
